CREATE TABLE `cash_mt4_account_type` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`metaserver_id` INT(11) NOT NULL DEFAULT '0',
	`platform_type` INT(11) NOT NULL,
	`platform_name` VARCHAR(16) NOT NULL DEFAULT '',
	`type_id` INT(11) NOT NULL,
	`type_name` VARCHAR(50) NOT NULL,
	`company` INT(11) NOT NULL,
	`group_creation` VARCHAR(50) NULL DEFAULT NULL,
	`leverage` INT(11) NULL DEFAULT NULL,
	`min_account_num` INT(11) NULL DEFAULT NULL,
	`max_account_num` INT(11) NULL DEFAULT NULL,
	`is_public` TINYINT(4) NOT NULL DEFAULT '0',
	`commission` DOUBLE NULL DEFAULT '0',
	`min_first_depo` DOUBLE NOT NULL DEFAULT '0',
	`min_lot` DOUBLE NULL DEFAULT '0',
	`max_lot` DOUBLE NOT NULL DEFAULT '0',
	`spread` DOUBLE NULL DEFAULT '0',
	`swap_charged` TINYINT(4) NOT NULL DEFAULT '0',
	`symbol_suffix` VARCHAR(20) NULL DEFAULT NULL,
	`products` VARCHAR(50) NULL DEFAULT 'All',
	`min_po` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `cmat_unique` (`metaserver_id`, `platform_type`, `type_id`, `company`),
	INDEX `cmat_platform_name` (`platform_name`),
	INDEX `cmat_type_id` (`type_id`),
	INDEX `cmat_type_name` (`type_name`),
	INDEX `cmat_company` (`company`),
	INDEX `cmat_platform_type` (`platform_type`),
	INDEX `cmat_group` (`group_creation`),
	INDEX `metaserver_id` (`metaserver_id`)
)
AUTO_INCREMENT=57
;
