Table "account_marketing_copy" {
  "mt4acc" VARCHAR(20) [not null]
  "marketing" INT(11) [not null, default: "0", note: 'follow-up']
  "maintenance" INT(11) [not null, default: "0"]
  "active" TINYINT(4) [not null]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]

Indexes {
  mt4acc [name: "mt4acc"]
  marketing [name: "marketing"]
  maintenance [name: "maintenance"]
}
}

Table "account_marketing_mtc" {
  "mt4acc" VARCHAR(20) [not null]
  "marketing" INT(11) [not null, default: "0", note: 'maintenance']
  "active" DATETIME [not null]
  "chop" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]

Indexes {
  mt4acc [name: "mt4acc"]
  marketing [name: "marketing"]
}
}

Table "account_marketing" {
  "mt4acc" VARCHAR(20) [not null]
  "marketing" INT(11) [not null, default: "0", note: 'follow-up']
  "active" DATETIME [not null]
  "chop" DATETIME [not null, default: "1970-01-01 00:00:00"]
  "lastmodified" INT(11) [not null]
  "modifiedby" INT(11) [not null, default: "0"]

Indexes {
  mt4acc [name: "mt4acc"]
  marketing [name: "marketing"]
}
}

Table "api_user" {
  "clientid" INT(11) [pk, not null, increment]
  "userid" INT(5) [not null]
  "clientname" VARCHAR(20) [not null]
  "clientip" TEXT [not null]
  "api_key" VARCHAR(20) [not null]
  "active" SMALLINT(1) [not null, default: "1"]
  "ValidateEmail" SMALLINT(1) [not null, default: "0"]
  "ValidateUserName" SMALLINT(1) [not null, default: "0"]
  "ValidateAffiliate" SMALLINT(1) [not null, default: "0"]
  "GetUserDetail" SMALLINT(1) [not null, default: "0"]
  "RegisterUser" SMALLINT(1) [not null, default: "0"]
  "RegisterAffiliate" SMALLINT(1) [not null, default: "0"]
  "UpdateParent" SMALLINT(1) [not null, default: "0"]
  "LinkTFAccount" SMALLINT(1) [not null, default: "0"]
  "SendMailApi" SMALLINT(1) [not null, default: "0"]
  "ReqAccountMT4" SMALLINT(1) [not null, default: "0"]
  "PreCheckWithdrawal" SMALLINT(1) [not null, default: "0"]
  "ReqWithdraw" SMALLINT(1) [not null, default: "0"]
  "ReqAccountContest" SMALLINT(1) [not null, default: "0"]
  "UploadID" SMALLINT(6) [not null, default: "0"]
  "ReqAccountDemo" SMALLINT(6) [not null, default: "0"]

Indexes {
  api_key [unique, name: "api_key"]
}
}

Table "birth_log" {
  "user_id" INT(5) [not null]
  "years" INT(4) [not null]
  "sender_id" INT(5) [not null]
  "time" INT(10) [not null]
  "claim" INT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
}
}

Table "cash_config" {
  "id" INT(11) [pk, not null, increment]
  "name" VARCHAR(64) [default: NULL]
  "value" TEXT [default: NULL]

Indexes {
  name [unique, name: "name"]
}
}

Table "cash_group" {
  "id" INT(11) [pk, not null, increment]
  "company" INT(11) [not null, default: "0"]
  "group" VARCHAR(16) [not null]
  "rateid" TINYINT(4) [not null, default: "0"]
  "rate" VARCHAR(16) [not null]
  "complete_depo" TINYINT(4) [not null, default: "0"]
  "approve_wd" TINYINT(4) [not null, default: "0"]
  "cashback" TINYINT(4) [not null, default: "0"]

Indexes {
  (company, group) [unique, name: "cash_group_company_group"]
  company [name: "cash_group_company"]
  group [name: "cash_group_group"]
  cashback [name: "cash_group_cashback"]
}
}

Table "cash_internal_transfer" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(11) [default: NULL]
  "creator" INT(11) [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_note" TEXT [default: NULL]
  "status" TINYINT(4) [not null, default: "0", note: '0: pending, 1: success, 2: refuse']
  "source_account" INT(11) [default: NULL]
  "source_metaserver" INT(11) [not null, default: "1"]
  "source_group" VARCHAR(16) [default: NULL]
  "source_rate" TINYINT(4) [default: NULL]
  "source_rateval" INT(11) [default: NULL]
  "source_order" INT(11) [default: NULL]
  "source_amount" DOUBLE [default: NULL]
  "source_comment" VARCHAR(32) [default: NULL]
  "target_account" INT(11) [default: NULL]
  "target_metaserver" INT(11) [not null, default: "1"]
  "target_group" VARCHAR(16) [default: NULL]
  "target_rate" TINYINT(4) [default: NULL]
  "target_rateval" INT(11) [default: NULL]
  "target_order" INT(11) [default: NULL]
  "target_amount" DOUBLE [default: NULL]
  "target_comment" VARCHAR(32) [default: NULL]
  "created_at" DATETIME [default: NULL]
  "done_at" DATETIME [default: NULL]

Indexes {
  source_order [unique, name: "source_order"]
  target_order [unique, name: "target_order"]
  source_metaserver [name: "source_metaserver"]
  target_metaserver [name: "target_metaserver"]
}
}

Table "cash_meta_server" {
  "id" INT(11) [pk, not null, increment]
  "platform_type" TINYINT(4) [not null]
  "public_name" VARCHAR(64) [not null]
  "private_name" VARCHAR(64) [not null]
  "active" TINYINT(1) [not null, default: "1"]

Indexes {
  platform_type [name: "platform_type"]
  public_name [name: "public_name"]
  private_name [name: "private_name"]
}
}

Table "cash_mt4_account_type" {
  "id" INT(11) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "0"]
  "platform_type" INT(11) [not null]
  "platform_name" VARCHAR(16) [not null, default: ""]
  "type_id" INT(11) [not null]
  "type_name" VARCHAR(50) [not null]
  "company" INT(11) [not null]
  "group_creation" VARCHAR(50) [default: NULL]
  "leverage" INT(11) [default: NULL]
  "min_account_num" INT(11) [default: NULL]
  "max_account_num" INT(11) [default: NULL]
  "is_public" TINYINT(4) [not null, default: "0"]
  "commission" DOUBLE [default: "0"]
  "min_first_depo" DOUBLE [not null, default: "0"]
  "min_lot" DOUBLE [default: "0"]
  "max_lot" DOUBLE [not null, default: "0"]
  "spread" DOUBLE [default: "0"]
  "swap_charged" TINYINT(4) [not null, default: "0"]
  "symbol_suffix" VARCHAR(20) [default: NULL]
  "products" VARCHAR(50) [default: "All"]
  "min_po" TEXT [default: NULL]

Indexes {
  (metaserver_id, platform_type, type_id, company) [unique, name: "cmat_unique"]
  platform_name [name: "cmat_platform_name"]
  type_id [name: "cmat_type_id"]
  type_name [name: "cmat_type_name"]
  company [name: "cmat_company"]
  platform_type [name: "cmat_platform_type"]
  group_creation [name: "cmat_group"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "cash_mt4_account" {
  "id" INT(11) [pk, not null, increment]
  "mt4id" INT(11) [not null]
  "metaserver_id" INT(11) [not null, default: "0"]
  "platform_type" INT(11) [not null, default: "0"]
  "user_id" INT(11) [not null]
  "taken" TINYINT(4) [not null, default: "0"]
  "acc_type" TINYINT(4) [not null, default: `-1`]
  "custom" TINYINT(4) [not null, default: "0"]
  "error_reason" TEXT [default: NULL]

Indexes {
  (metaserver_id, mt4id) [unique, name: "mt4id_unique"]
  user_id [name: "user_id"]
  (acc_type, taken) [name: "acc_type"]
  custom [name: "custom"]
  metaserver_id [name: "metaserver_id"]
  platform_type [name: "platform_type"]
  mt4id [name: "mt4id"]
}
}

Table "companybank" {
  "bank_id" INT(5) [pk, not null, increment]
  "curr_id" INT(5) [not null]
  "bank_name" VARCHAR(100) [not null]
  "bank_acc_no" VARCHAR(20) [not null]
  "bank_acc_name" VARCHAR(100) [not null]
}

Table "contest_schedule" {
  "id" INT(11) [pk, not null, increment]
  "period" VARCHAR(50) [not null, default: ""]
  "eventstart" DATE [not null]
  "eventend" DATE [not null]
  "regstart" DATE [not null]
  "regend" DATE [not null]
  "infowinner" DATE [not null]
  "active" TINYINT(4) [default: "1"]
}

Table "countries" {
  "country_id" INT(11) [pk, not null, increment]
  "code" CHAR(2) [not null, note: 'Two-letter country code (ISO 3166-1 alpha-2)']
  "name" VARCHAR(64) [not null, note: 'English country name']
  "full_name" VARCHAR(128) [not null, note: 'Full English country name']
  "iso3" CHAR(3) [not null, note: 'Three-letter country code (ISO 3166-1 alpha-3)']
  "number" SMALLINT(3) [not null, note: 'Three-digit country number (ISO 3166-1 numeric)']
  "continent_code" CHAR(2) [not null]
  "display_order" INT(3) [not null, default: "900"]

Indexes {
  code [unique, name: "idx_code"]
  continent_code [name: "idx_continent_code"]
}
}

Table "country" {
  "id" VARCHAR(2) [pk, not null]
  "name" VARCHAR(64) [not null]
  "telephone_code" VARCHAR(10) [default: NULL]
}

Table "demo_contest_2011" {
  "user_id" INT(5) [not null]
  "user_mt4id" INT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "demo_contest_2012" {
  "user_id" INT(5) [not null]
  "user_mt4id" INT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "demo_contest_2013" {
  "user_id" INT(5) [pk, not null]
  "user_mt4id" INT(15) [not null]
  "password" VARCHAR(8) [not null]
  "mail_sent" INT(1) [not null, default: "0"]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "deposit_state" {
  "deposit_id" INT(11) [pk, not null]
  "method" VARCHAR(50) [default: NULL]
  "method_other" VARCHAR(50) [default: NULL]
  "cashier" INT(11) [default: NULL]
  "cashier_approval" TINYINT(4) [default: NULL]
  "cashier_approval_tm" DATETIME [default: NULL]
  "cashier_note" TEXT [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_order_num" INT(11) [default: NULL]
  "settle_order_tm" DATETIME [default: NULL]
  "settle_note" TEXT [default: NULL]
  "last_modify" DATETIME [default: NULL]
}

Table "deposit" {
  "id" INT(10) [pk, not null, increment]
  "metaserver_id" INT(10) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(20) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "ref_number" VARCHAR(50) [default: ""]
  "nominal" DECIMAL(15,2) [not null]
  "rate" INT(1) [not null, default: "0"]
  "rateval" INT(6) [not null, default: "100000"]
  "fg_bankname" VARCHAR(20) [not null]
  "fg_bankaccno" VARCHAR(20) [not null]
  "fg_bankreg" VARCHAR(100) [not null]
  "time" INT(10) [not null]
  "tipe" INT(1) [not null]
  "status" INT(1) [not null, default: "0"]
  "platform" INT(1) [not null, default: "0"]
  "acc_type" INT(1) [not null, default: "0"]
  "paypal" VARCHAR(50) [default: ""]
  "fee" FLOAT [not null, default: "0"]
  "origin" TINYINT(1) [not null, default: "0"]
  "fxdana" TINYINT(1) [default: NULL, note: '7: ?']
  "method" VARCHAR(50) [default: NULL]
  "method_other" VARCHAR(50) [default: NULL]
  "cashier" INT(11) [default: NULL]
  "cashier_approval" TINYINT(4) [default: NULL]
  "cashier_approval_tm" DATETIME [default: NULL]
  "cashier_note" TEXT [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_order_num" INT(11) [default: NULL]
  "settle_order_tm" DATETIME [default: NULL]
  "settle_note" TEXT [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]
  "campaignid" VARCHAR(128) [default: NULL]
  "adid" VARCHAR(128) [default: NULL]

Indexes {
  user_id [name: "user_id"]
  mt4id [name: "mt4id"]
  status [name: "status"]
  metaserver_id [name: "metaserver_id"]
  campaignid [name: "campaignid"]
  adid [name: "adid"]
}
}

Table "email_content_var" {
  "content_id" INT(11) [not null]
  "var_id" INT(11) [not null]

Indexes {
  (content_id, var_id) [pk]
}
}

Table "email_content" {
  "id" INT(11) [pk, not null, increment]
  "email_id" INT(11) [default: NULL]
  "action" INT(11) [default: NULL, note: '0: Admin, 1: User']
  "content" LONGTEXT [not null]
}

Table "email_temp" {
  "email" VARCHAR(255) [not null]
}

Table "email_var" {
  "id" INT(11) [pk, not null, increment]
  "name" VARCHAR(50) [default: NULL]
}

Table "email_whitelabel" {
  "id" INT(11) [pk, not null, increment]
  "email_id" INT(11) [not null]
  "company" INT(11) [not null]

Indexes {
  (email_id, company) [unique, name: "email_company"]
  company [name: "company"]
  email_id [name: "email_id"]
}
}

Table "email" {
  "id" INT(11) [pk, not null, increment]
  "content_id" INT(11) [not null]
  "subject" TEXT [not null]
  "from_name" TEXT [not null]
  "from_email" TEXT [not null]
  "to_name" TEXT [not null]
  "to_email" TEXT [not null]
  "cc_name" TEXT [not null]
  "cc_email" TEXT [not null]
  "bcc_name" TEXT [not null]
  "bcc_email" TEXT [not null]
  "lang" INT(11) [not null, default: "0", note: '0: Indonesia, 1: English']
  "smtp_host" TEXT [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null, default: "0"]
  "email" TEXT [not null]
  "password" TEXT [default: NULL]
}

Table "euro_2012" {
  "euro_2012_id" INT(11) [not null, increment]
  "name" VARCHAR(64) [not null]
  "user_name" VARCHAR(64) [not null]
  "email" VARCHAR(64) [not null]
  "pass" VARCHAR(64) [not null]
  "hp" VARCHAR(14) [not null]
  "existing" INT(1) [not null, default: "0"]
  "activated" INT(1) [not null]
  "verify_string" VARCHAR(128) [not null]
  "time" INT(64) [not null]

Indexes {
  email [unique, name: "email"]
  euro_2012_id [name: "user_id"]
}
}

Table "fxd_wd_requests" {
  "id" INT(11) [pk, not null, increment]
  "account" INT(11) [not null]
  "event" INT(11) [not null]
  "transid" INT(11) [default: NULL, note: 'if status not 0, wd sudah disubmit & inputkan transID']
  "stat_traders" TINYINT(1) [not null, default: "0", note: '0 pending, 1 approved, 2 rejected']
  "reconnect" TINYINT(1) [not null, default: "0", note: '0 suspend, 1 active, 2 inactive']
  "margin" DOUBLE [default: NULL]
  "totalDepo" DOUBLE [default: NULL]
  "balance" DOUBLE [default: NULL]
  "minDepo" DOUBLE [default: NULL]
  "unpaidMngFee" DOUBLE [default: NULL]
  "penalty" DOUBLE [default: NULL]

Indexes {
  account [name: "account"]
}
}

Table "gema_aff" {
  "user_id" INT(5) [pk, not null, increment]
  "user_level" INT(1) [not null, default: "1"]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(25) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_birth" DATE [not null, default: "0000-00-00"]
  "user_blntgl" VARCHAR(4) [not null, default: "0000"]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "user_mt4id" VARCHAR(255) [not null]
  "user_bbpin" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [not null]
  "real_acc" INT(1) [not null, default: "0"]
  "euro2012" INT(1) [not null, default: "0"]
  "country" VARCHAR(2) [not null, default: "id"]
  "city" VARCHAR(50) [not null]
  "paypal" VARCHAR(50) [not null]
  "origin" TINYINT(1) [not null, default: "0"]

Indexes {
  user_name [unique, name: "user_name"]
  user_email [unique, name: "user_email"]
  user_referrer_id [name: "user_referrer_id"]
}
}

Table "gema_users" {
  "user_id" INT(5) [pk, not null, increment]
  "user_level" INT(1) [not null, default: "1"]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(25) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_birth" DATE [not null, default: "0000-00-00"]
  "user_blntgl" VARCHAR(4) [not null, default: "0000"]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "user_mt4id" VARCHAR(255) [not null]
  "user_bbpin" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [not null]
  "real_acc" INT(1) [not null, default: "0"]
  "euro2012" INT(1) [not null, default: "0"]
  "country" VARCHAR(2) [not null, default: "id"]
  "city" VARCHAR(50) [not null]
  "paypal" VARCHAR(50) [not null]
  "origin" TINYINT(1) [not null, default: "0"]

Indexes {
  user_name [unique, name: "user_name"]
  user_email [unique, name: "user_email"]
  user_referrer_id [name: "user_referrer_id"]
}
}

Table "jiboy" {
  "userid" INT(11) [not null]
}

Table "leverage_1_200" {
  "mt4id" INT(11) [pk, not null]
  "email" VARCHAR(50) [not null]
  "fullname" VARCHAR(50) [not null]
  "request_time" INT(10) [not null]
  "created_time" INT(10) [not null]
}

Table "lock_process" {
  "event" VARCHAR(50) [pk, not null]
}

Table "log_old" {
  "id" INT(10) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "action" VARCHAR(25) [not null]
  "ip" VARCHAR(15) [not null]
  "browser" VARCHAR(255) [not null]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "log" {
  "id" INT(10) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "action" VARCHAR(255) [not null]
  "ip" VARCHAR(15) [not null]
  "browser" VARCHAR(255) [not null]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
  action [name: "action"]
  ip [name: "ip"]
  browser [name: "browser"]
}
}

Table "lot" {
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(10) [not null]
  "year" INT(4) [not null]
  "jan" DECIMAL(10,2) [not null]
  "feb" DECIMAL(10,2) [not null]
  "mar" DECIMAL(10,2) [not null]
  "apr" DECIMAL(10,2) [not null]
  "may" DECIMAL(10,2) [not null]
  "jun" DECIMAL(10,2) [not null]
  "jul" DECIMAL(10,2) [not null]
  "aug" DECIMAL(10,2) [not null]
  "sep" DECIMAL(10,2) [not null]
  "oct" DECIMAL(10,2) [not null]
  "nov" DECIMAL(10,2) [not null]
  "des" DECIMAL(10,2) [not null]
  "time" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
  mt4id [name: "mt4id"]
  year [name: "year"]
  (year, user_id, mt4id) [pk]
}
}

Table "mail_mrg" {
  "subject_0" LONGTEXT [not null]
  "from_name_0" LONGTEXT [not null]
  "from_email_0" LONGTEXT [not null]
  "to_name_0" LONGTEXT [not null]
  "to_email_0" LONGTEXT [not null]
  "cc_name_0" LONGTEXT [not null]
  "cc_email_0" LONGTEXT [not null]
  "bcc_name_0" LONGTEXT [not null]
  "bcc_email_0" LONGTEXT [not null]
  "content_00" LONGTEXT [not null]
  "content_01" LONGTEXT [not null]
  "subject_1" LONGTEXT [not null]
  "from_name_1" LONGTEXT [not null]
  "from_email_1" LONGTEXT [not null]
  "to_name_1" LONGTEXT [not null]
  "to_email_1" LONGTEXT [not null]
  "cc_name_1" LONGTEXT [not null]
  "cc_email_1" LONGTEXT [not null]
  "bcc_name_1" LONGTEXT [not null]
  "bcc_email_1" LONGTEXT [not null]
  "content_10" LONGTEXT [not null]
  "content_11" LONGTEXT [not null]
  "content_12" LONGTEXT [not null]
  "content_13" LONGTEXT [not null]
  "subject_2" LONGTEXT [not null]
  "from_name_2" LONGTEXT [not null]
  "from_email_2" LONGTEXT [not null]
  "to_name_2" LONGTEXT [not null]
  "to_email_2" LONGTEXT [not null]
  "cc_name_2" LONGTEXT [not null]
  "cc_email_2" LONGTEXT [not null]
  "bcc_name_2" LONGTEXT [not null]
  "bcc_email_2" LONGTEXT [not null]
  "content_20" LONGTEXT [not null]
  "content_21" LONGTEXT [not null]
  "subject_3" LONGTEXT [not null]
  "from_name_3" LONGTEXT [not null]
  "from_email_3" LONGTEXT [not null]
  "to_name_3" LONGTEXT [not null]
  "to_email_3" LONGTEXT [not null]
  "cc_name_3" LONGTEXT [not null]
  "cc_email_3" LONGTEXT [not null]
  "bcc_name_3" LONGTEXT [not null]
  "bcc_email_3" LONGTEXT [not null]
  "content_30" LONGTEXT [not null]
  "content_31" LONGTEXT [not null]
  "subject_4" LONGTEXT [not null]
  "from_name_4" LONGTEXT [not null]
  "from_email_4" LONGTEXT [not null]
  "to_name_4" LONGTEXT [not null]
  "to_email_4" LONGTEXT [not null]
  "cc_name_4" LONGTEXT [not null]
  "cc_email_4" LONGTEXT [not null]
  "bcc_name_4" LONGTEXT [not null]
  "bcc_email_4" LONGTEXT [not null]
  "content_40" LONGTEXT [not null]
  "content_41" LONGTEXT [not null]
  "smtp_host" VARCHAR(50) [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(50) [not null]
  "subject_6" LONGTEXT [not null]
  "from_name_6" LONGTEXT [not null]
  "from_email_6" LONGTEXT [not null]
  "to_name_6" LONGTEXT [not null]
  "to_email_6" LONGTEXT [not null]
  "cc_name_6" LONGTEXT [not null]
  "cc_email_6" LONGTEXT [not null]
  "bcc_name_6" LONGTEXT [not null]
  "bcc_email_6" LONGTEXT [not null]
  "content_60" LONGTEXT [not null]
  "content_61" LONGTEXT [not null]
  "subject_7" LONGTEXT [not null]
  "from_name_7" LONGTEXT [not null]
  "from_email_7" LONGTEXT [not null]
  "to_name_7" LONGTEXT [not null]
  "to_email_7" LONGTEXT [not null]
  "cc_name_7" LONGTEXT [not null]
  "cc_email_7" LONGTEXT [not null]
  "bcc_name_7" LONGTEXT [not null]
  "bcc_email_7" LONGTEXT [not null]
  "content_70" LONGTEXT [not null]
  "content_71" LONGTEXT [not null]
  "subject_8" LONGTEXT [not null]
  "from_name_8" LONGTEXT [not null]
  "from_email_8" LONGTEXT [not null]
  "to_name_8" LONGTEXT [not null]
  "to_email_8" LONGTEXT [not null]
  "cc_name_8" LONGTEXT [not null]
  "cc_email_8" LONGTEXT [not null]
  "bcc_name_8" LONGTEXT [not null]
  "bcc_email_8" LONGTEXT [not null]
  "content_80" LONGTEXT [not null]
  "content_81" LONGTEXT [not null]
  "subject_9" LONGTEXT [not null]
  "from_name_9" LONGTEXT [not null]
  "from_email_9" LONGTEXT [not null]
  "to_name_9" LONGTEXT [not null]
  "to_email_9" LONGTEXT [not null]
  "cc_name_9" LONGTEXT [not null]
  "cc_email_9" LONGTEXT [not null]
  "bcc_name_9" LONGTEXT [not null]
  "bcc_email_9" LONGTEXT [not null]
  "content_90" LONGTEXT [not null]
  "content_91" LONGTEXT [not null]
  "subject_10" LONGTEXT [not null]
  "from_name_10" LONGTEXT [not null]
  "from_email_10" LONGTEXT [not null]
  "to_name_10" LONGTEXT [not null]
  "to_email_10" LONGTEXT [not null]
  "cc_name_10" LONGTEXT [not null]
  "cc_email_10" LONGTEXT [not null]
  "bcc_name_10" LONGTEXT [not null]
  "bcc_email_10" LONGTEXT [not null]
  "content_100" LONGTEXT [not null]
  "content_101" LONGTEXT [not null]
  "subject_11" LONGTEXT [not null]
  "from_name_11" LONGTEXT [not null]
  "from_email_11" LONGTEXT [not null]
  "to_name_11" LONGTEXT [not null]
  "to_email_11" LONGTEXT [not null]
  "cc_name_11" LONGTEXT [not null]
  "cc_email_11" LONGTEXT [not null]
  "bcc_name_11" LONGTEXT [not null]
  "bcc_email_11" LONGTEXT [not null]
  "content_110" LONGTEXT [not null]
  "content_111" LONGTEXT [not null]
  "subject_12" LONGTEXT [not null]
  "from_name_12" LONGTEXT [not null]
  "from_email_12" LONGTEXT [not null]
  "to_name_12" LONGTEXT [not null]
  "to_email_12" LONGTEXT [not null]
  "cc_name_12" LONGTEXT [not null]
  "cc_email_12" LONGTEXT [not null]
  "bcc_name_12" LONGTEXT [not null]
  "bcc_email_12" LONGTEXT [not null]
  "content_120" LONGTEXT [not null]
  "content_121" LONGTEXT [not null]
  "subject_13" LONGTEXT [not null]
  "from_name_13" LONGTEXT [not null]
  "from_email_13" LONGTEXT [not null]
  "to_name_13" LONGTEXT [not null]
  "to_email_13" LONGTEXT [not null]
  "cc_name_13" LONGTEXT [not null]
  "cc_email_13" LONGTEXT [not null]
  "bcc_name_13" LONGTEXT [not null]
  "bcc_email_13" LONGTEXT [not null]
  "content_130" LONGTEXT [not null]
  "content_131" LONGTEXT [not null]
  "subject_14" LONGTEXT [not null]
  "from_name_14" LONGTEXT [not null]
  "from_email_14" LONGTEXT [not null]
  "to_name_14" LONGTEXT [not null]
  "to_email_14" LONGTEXT [not null]
  "cc_name_14" LONGTEXT [not null]
  "cc_email_14" LONGTEXT [not null]
  "bcc_name_14" LONGTEXT [not null]
  "bcc_email_14" LONGTEXT [not null]
  "content_140" LONGTEXT [not null]
  "content_141" LONGTEXT [not null]
  "subject_15" LONGTEXT [not null]
  "from_name_15" LONGTEXT [not null]
  "from_email_15" LONGTEXT [not null]
  "to_name_15" LONGTEXT [not null]
  "to_email_15" LONGTEXT [not null]
  "cc_name_15" LONGTEXT [not null]
  "cc_email_15" LONGTEXT [not null]
  "bcc_name_15" LONGTEXT [not null]
  "bcc_email_15" LONGTEXT [not null]
  "content_150" LONGTEXT [not null]
  "content_151" LONGTEXT [not null]
  "subject_16" LONGTEXT [not null]
  "from_name_16" LONGTEXT [not null]
  "from_email_16" LONGTEXT [not null]
  "to_name_16" LONGTEXT [not null]
  "to_email_16" LONGTEXT [not null]
  "cc_name_16" LONGTEXT [not null]
  "cc_email_16" LONGTEXT [not null]
  "bcc_name_16" LONGTEXT [not null]
  "bcc_email_16" LONGTEXT [not null]
  "content_160" LONGTEXT [not null]
  "content_161" LONGTEXT [not null]
  "subject_17" LONGTEXT [not null]
  "from_name_17" LONGTEXT [not null]
  "from_email_17" LONGTEXT [not null]
  "to_name_17" LONGTEXT [not null]
  "to_email_17" LONGTEXT [not null]
  "cc_name_17" LONGTEXT [not null]
  "cc_email_17" LONGTEXT [not null]
  "bcc_name_17" LONGTEXT [not null]
  "bcc_email_17" LONGTEXT [not null]
  "content_170" LONGTEXT [not null]
  "content_171" LONGTEXT [not null]
  "subject_18" LONGTEXT [not null]
  "from_name_18" LONGTEXT [not null]
  "from_email_18" LONGTEXT [not null]
  "to_name_18" LONGTEXT [not null]
  "to_email_18" LONGTEXT [not null]
  "cc_name_18" LONGTEXT [not null]
  "cc_email_18" LONGTEXT [not null]
  "bcc_name_18" LONGTEXT [not null]
  "bcc_email_18" LONGTEXT [not null]
  "content_180" LONGTEXT [not null]
  "content_181" LONGTEXT [not null]
  "subject_19" LONGTEXT [not null]
  "from_name_19" LONGTEXT [not null]
  "from_email_19" LONGTEXT [not null]
  "to_name_19" LONGTEXT [not null]
  "to_email_19" LONGTEXT [not null]
  "cc_name_19" LONGTEXT [not null]
  "cc_email_19" LONGTEXT [not null]
  "bcc_name_19" LONGTEXT [not null]
  "bcc_email_19" LONGTEXT [not null]
  "content_190" LONGTEXT [not null]
  "content_191" LONGTEXT [not null]
  "subject_20" LONGTEXT [not null]
  "from_name_20" LONGTEXT [not null]
  "from_email_20" LONGTEXT [not null]
  "to_name_20" LONGTEXT [not null]
  "to_email_20" LONGTEXT [not null]
  "cc_name_20" LONGTEXT [not null]
  "cc_email_20" LONGTEXT [not null]
  "bcc_name_20" LONGTEXT [not null]
  "bcc_email_20" LONGTEXT [not null]
  "content_200" LONGTEXT [not null]
  "content_201" LONGTEXT [not null]
  "subject_21" LONGTEXT [not null]
  "from_name_21" LONGTEXT [not null]
  "from_email_21" LONGTEXT [not null]
  "to_name_21" LONGTEXT [not null]
  "to_email_21" LONGTEXT [not null]
  "cc_name_21" LONGTEXT [not null]
  "cc_email_21" LONGTEXT [not null]
  "bcc_name_21" LONGTEXT [not null]
  "bcc_email_21" LONGTEXT [not null]
  "content_210" LONGTEXT [not null]
  "content_211" LONGTEXT [not null]
  "subject_22" LONGTEXT [not null]
  "from_name_22" LONGTEXT [not null]
  "from_email_22" LONGTEXT [not null]
  "to_name_22" LONGTEXT [not null]
  "to_email_22" LONGTEXT [not null]
  "cc_name_22" LONGTEXT [not null]
  "cc_email_22" LONGTEXT [not null]
  "bcc_name_22" LONGTEXT [not null]
  "bcc_email_22" LONGTEXT [not null]
  "content_220" LONGTEXT [not null]
  "content_221" LONGTEXT [not null]
  "subject_23" LONGTEXT [not null]
  "from_name_23" LONGTEXT [not null]
  "from_email_23" LONGTEXT [not null]
  "to_name_23" LONGTEXT [not null]
  "to_email_23" LONGTEXT [not null]
  "cc_name_23" LONGTEXT [not null]
  "cc_email_23" LONGTEXT [not null]
  "bcc_name_23" LONGTEXT [not null]
  "bcc_email_23" LONGTEXT [not null]
  "content_230" LONGTEXT [not null]
  "content_231" LONGTEXT [not null]
  "subject_24" LONGTEXT [not null]
  "from_name_24" LONGTEXT [not null]
  "from_email_24" LONGTEXT [not null]
  "to_name_24" LONGTEXT [not null]
  "to_email_24" LONGTEXT [not null]
  "cc_name_24" LONGTEXT [not null]
  "cc_email_24" LONGTEXT [not null]
  "bcc_name_24" LONGTEXT [not null]
  "bcc_email_24" LONGTEXT [not null]
  "content_240" LONGTEXT [not null]
  "content_241" LONGTEXT [not null]
  "subject_25" LONGTEXT [not null]
  "from_name_25" LONGTEXT [not null]
  "from_email_25" LONGTEXT [not null]
  "to_name_25" LONGTEXT [not null]
  "to_email_25" LONGTEXT [not null]
  "cc_name_25" LONGTEXT [not null]
  "cc_email_25" LONGTEXT [not null]
  "bcc_name_25" LONGTEXT [not null]
  "bcc_email_25" LONGTEXT [not null]
  "content_250" LONGTEXT [not null]
  "content_251" LONGTEXT [not null]
  "subject_26" LONGTEXT [not null]
  "from_name_26" LONGTEXT [not null]
  "from_email_26" LONGTEXT [not null]
  "to_name_26" LONGTEXT [not null]
  "to_email_26" LONGTEXT [not null]
  "cc_name_26" LONGTEXT [not null]
  "cc_email_26" LONGTEXT [not null]
  "bcc_name_26" LONGTEXT [not null]
  "bcc_email_26" LONGTEXT [not null]
  "content_260" LONGTEXT [not null]
  "content_261" LONGTEXT [not null]
  "subject_27" LONGTEXT [not null]
  "from_name_27" LONGTEXT [not null]
  "from_email_27" LONGTEXT [not null]
  "to_name_27" LONGTEXT [not null]
  "to_email_27" LONGTEXT [not null]
  "cc_name_27" LONGTEXT [not null]
  "cc_email_27" LONGTEXT [not null]
  "bcc_name_27" LONGTEXT [not null]
  "bcc_email_27" LONGTEXT [not null]
  "content_270" LONGTEXT [not null]
  "content_271" LONGTEXT [not null]
}

Table "mail" {
  "subject_0" LONGTEXT [not null]
  "from_name_0" LONGTEXT [not null]
  "from_email_0" LONGTEXT [not null]
  "to_name_0" LONGTEXT [not null]
  "to_email_0" LONGTEXT [not null]
  "cc_name_0" LONGTEXT [not null]
  "cc_email_0" LONGTEXT [not null]
  "bcc_name_0" LONGTEXT [not null]
  "bcc_email_0" LONGTEXT [not null]
  "content_00" LONGTEXT [not null]
  "content_01" LONGTEXT [not null]
  "subject_1" LONGTEXT [not null]
  "from_name_1" LONGTEXT [not null]
  "from_email_1" LONGTEXT [not null]
  "to_name_1" LONGTEXT [not null]
  "to_email_1" LONGTEXT [not null]
  "cc_name_1" LONGTEXT [not null]
  "cc_email_1" LONGTEXT [not null]
  "bcc_name_1" LONGTEXT [not null]
  "bcc_email_1" LONGTEXT [not null]
  "content_10" LONGTEXT [not null]
  "content_11" LONGTEXT [not null]
  "content_12" LONGTEXT [not null]
  "content_13" LONGTEXT [not null]
  "subject_2" LONGTEXT [not null]
  "from_name_2" LONGTEXT [not null]
  "from_email_2" LONGTEXT [not null]
  "to_name_2" LONGTEXT [not null]
  "to_email_2" LONGTEXT [not null]
  "cc_name_2" LONGTEXT [not null]
  "cc_email_2" LONGTEXT [not null]
  "bcc_name_2" LONGTEXT [not null]
  "bcc_email_2" LONGTEXT [not null]
  "content_20" LONGTEXT [not null]
  "content_21" LONGTEXT [not null]
  "subject_3" LONGTEXT [not null]
  "from_name_3" LONGTEXT [not null]
  "from_email_3" LONGTEXT [not null]
  "to_name_3" LONGTEXT [not null]
  "to_email_3" LONGTEXT [not null]
  "cc_name_3" LONGTEXT [not null]
  "cc_email_3" LONGTEXT [not null]
  "bcc_name_3" LONGTEXT [not null]
  "bcc_email_3" LONGTEXT [not null]
  "content_30" LONGTEXT [not null]
  "content_31" LONGTEXT [not null]
  "subject_4" LONGTEXT [not null]
  "from_name_4" LONGTEXT [not null]
  "from_email_4" LONGTEXT [not null]
  "to_name_4" LONGTEXT [not null]
  "to_email_4" LONGTEXT [not null]
  "cc_name_4" LONGTEXT [not null]
  "cc_email_4" LONGTEXT [not null]
  "bcc_name_4" LONGTEXT [not null]
  "bcc_email_4" LONGTEXT [not null]
  "content_40" LONGTEXT [not null]
  "content_41" LONGTEXT [not null]
  "smtp_host" VARCHAR(50) [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(50) [not null]
  "subject_6" LONGTEXT [not null]
  "from_name_6" LONGTEXT [not null]
  "from_email_6" LONGTEXT [not null]
  "to_name_6" LONGTEXT [not null]
  "to_email_6" LONGTEXT [not null]
  "cc_name_6" LONGTEXT [not null]
  "cc_email_6" LONGTEXT [not null]
  "bcc_name_6" LONGTEXT [not null]
  "bcc_email_6" LONGTEXT [not null]
  "content_60" LONGTEXT [not null]
  "content_61" LONGTEXT [not null]
  "subject_7" LONGTEXT [not null]
  "from_name_7" LONGTEXT [not null]
  "from_email_7" LONGTEXT [not null]
  "to_name_7" LONGTEXT [not null]
  "to_email_7" LONGTEXT [not null]
  "cc_name_7" LONGTEXT [not null]
  "cc_email_7" LONGTEXT [not null]
  "bcc_name_7" LONGTEXT [not null]
  "bcc_email_7" LONGTEXT [not null]
  "content_70" LONGTEXT [not null]
  "content_71" LONGTEXT [not null]
  "subject_8" LONGTEXT [not null]
  "from_name_8" LONGTEXT [not null]
  "from_email_8" LONGTEXT [not null]
  "to_name_8" LONGTEXT [not null]
  "to_email_8" LONGTEXT [not null]
  "cc_name_8" LONGTEXT [not null]
  "cc_email_8" LONGTEXT [not null]
  "bcc_name_8" LONGTEXT [not null]
  "bcc_email_8" LONGTEXT [not null]
  "content_80" LONGTEXT [not null]
  "content_81" LONGTEXT [not null]
  "subject_9" LONGTEXT [not null]
  "from_name_9" LONGTEXT [not null]
  "from_email_9" LONGTEXT [not null]
  "to_name_9" LONGTEXT [not null]
  "to_email_9" LONGTEXT [not null]
  "cc_name_9" LONGTEXT [not null]
  "cc_email_9" LONGTEXT [not null]
  "bcc_name_9" LONGTEXT [not null]
  "bcc_email_9" LONGTEXT [not null]
  "content_90" LONGTEXT [not null]
  "content_91" LONGTEXT [not null]
  "subject_10" LONGTEXT [not null]
  "from_name_10" LONGTEXT [not null]
  "from_email_10" LONGTEXT [not null]
  "to_name_10" LONGTEXT [not null]
  "to_email_10" LONGTEXT [not null]
  "cc_name_10" LONGTEXT [not null]
  "cc_email_10" LONGTEXT [not null]
  "bcc_name_10" LONGTEXT [not null]
  "bcc_email_10" LONGTEXT [not null]
  "content_100" LONGTEXT [not null]
  "content_101" LONGTEXT [not null]
  "subject_11" LONGTEXT [not null]
  "from_name_11" LONGTEXT [not null]
  "from_email_11" LONGTEXT [not null]
  "to_name_11" LONGTEXT [not null]
  "to_email_11" LONGTEXT [not null]
  "cc_name_11" LONGTEXT [not null]
  "cc_email_11" LONGTEXT [not null]
  "bcc_name_11" LONGTEXT [not null]
  "bcc_email_11" LONGTEXT [not null]
  "content_110" LONGTEXT [not null]
  "content_111" LONGTEXT [not null]
  "subject_12" LONGTEXT [not null]
  "from_name_12" LONGTEXT [not null]
  "from_email_12" LONGTEXT [not null]
  "to_name_12" LONGTEXT [not null]
  "to_email_12" LONGTEXT [not null]
  "cc_name_12" LONGTEXT [not null]
  "cc_email_12" LONGTEXT [not null]
  "bcc_name_12" LONGTEXT [not null]
  "bcc_email_12" LONGTEXT [not null]
  "content_120" LONGTEXT [not null]
  "content_121" LONGTEXT [not null]
  "subject_13" LONGTEXT [not null]
  "from_name_13" LONGTEXT [not null]
  "from_email_13" LONGTEXT [not null]
  "to_name_13" LONGTEXT [not null]
  "to_email_13" LONGTEXT [not null]
  "cc_name_13" LONGTEXT [not null]
  "cc_email_13" LONGTEXT [not null]
  "bcc_name_13" LONGTEXT [not null]
  "bcc_email_13" LONGTEXT [not null]
  "content_130" LONGTEXT [not null]
  "content_131" LONGTEXT [not null]
  "subject_14" LONGTEXT [not null]
  "from_name_14" LONGTEXT [not null]
  "from_email_14" LONGTEXT [not null]
  "to_name_14" LONGTEXT [not null]
  "to_email_14" LONGTEXT [not null]
  "cc_name_14" LONGTEXT [not null]
  "cc_email_14" LONGTEXT [not null]
  "bcc_name_14" LONGTEXT [not null]
  "bcc_email_14" LONGTEXT [not null]
  "content_140" LONGTEXT [not null]
  "content_141" LONGTEXT [not null]
  "subject_15" LONGTEXT [not null]
  "from_name_15" LONGTEXT [not null]
  "from_email_15" LONGTEXT [not null]
  "to_name_15" LONGTEXT [not null]
  "to_email_15" LONGTEXT [not null]
  "cc_name_15" LONGTEXT [not null]
  "cc_email_15" LONGTEXT [not null]
  "bcc_name_15" LONGTEXT [not null]
  "bcc_email_15" LONGTEXT [not null]
  "content_150" LONGTEXT [not null]
  "content_151" LONGTEXT [not null]
  "subject_16" LONGTEXT [not null]
  "from_name_16" LONGTEXT [not null]
  "from_email_16" LONGTEXT [not null]
  "to_name_16" LONGTEXT [not null]
  "to_email_16" LONGTEXT [not null]
  "cc_name_16" LONGTEXT [not null]
  "cc_email_16" LONGTEXT [not null]
  "bcc_name_16" LONGTEXT [not null]
  "bcc_email_16" LONGTEXT [not null]
  "content_160" LONGTEXT [not null]
  "content_161" LONGTEXT [not null]
  "subject_17" LONGTEXT [not null]
  "from_name_17" LONGTEXT [not null]
  "from_email_17" LONGTEXT [not null]
  "to_name_17" LONGTEXT [not null]
  "to_email_17" LONGTEXT [not null]
  "cc_name_17" LONGTEXT [not null]
  "cc_email_17" LONGTEXT [not null]
  "bcc_name_17" LONGTEXT [not null]
  "bcc_email_17" LONGTEXT [not null]
  "content_170" LONGTEXT [not null]
  "content_171" LONGTEXT [not null]
  "subject_18" LONGTEXT [not null]
  "from_name_18" LONGTEXT [not null]
  "from_email_18" LONGTEXT [not null]
  "to_name_18" LONGTEXT [not null]
  "to_email_18" LONGTEXT [not null]
  "cc_name_18" LONGTEXT [not null]
  "cc_email_18" LONGTEXT [not null]
  "bcc_name_18" LONGTEXT [not null]
  "bcc_email_18" LONGTEXT [not null]
  "content_180" LONGTEXT [not null]
  "content_181" LONGTEXT [not null]
  "subject_19" LONGTEXT [not null]
  "from_name_19" LONGTEXT [not null]
  "from_email_19" LONGTEXT [not null]
  "to_name_19" LONGTEXT [not null]
  "to_email_19" LONGTEXT [not null]
  "cc_name_19" LONGTEXT [not null]
  "cc_email_19" LONGTEXT [not null]
  "bcc_name_19" LONGTEXT [not null]
  "bcc_email_19" LONGTEXT [not null]
  "content_190" LONGTEXT [not null]
  "content_191" LONGTEXT [not null]
  "subject_20" LONGTEXT [not null]
  "from_name_20" LONGTEXT [not null]
  "from_email_20" LONGTEXT [not null]
  "to_name_20" LONGTEXT [not null]
  "to_email_20" LONGTEXT [not null]
  "cc_name_20" LONGTEXT [not null]
  "cc_email_20" LONGTEXT [not null]
  "bcc_name_20" LONGTEXT [not null]
  "bcc_email_20" LONGTEXT [not null]
  "content_200" LONGTEXT [not null]
  "content_201" LONGTEXT [not null]
  "subject_21" LONGTEXT [not null]
  "from_name_21" LONGTEXT [not null]
  "from_email_21" LONGTEXT [not null]
  "to_name_21" LONGTEXT [not null]
  "to_email_21" LONGTEXT [not null]
  "cc_name_21" LONGTEXT [not null]
  "cc_email_21" LONGTEXT [not null]
  "bcc_name_21" LONGTEXT [not null]
  "bcc_email_21" LONGTEXT [not null]
  "content_210" LONGTEXT [not null]
  "content_211" LONGTEXT [not null]
  "subject_22" LONGTEXT [not null]
  "from_name_22" LONGTEXT [not null]
  "from_email_22" LONGTEXT [not null]
  "to_name_22" LONGTEXT [not null]
  "to_email_22" LONGTEXT [not null]
  "cc_name_22" LONGTEXT [not null]
  "cc_email_22" LONGTEXT [not null]
  "bcc_name_22" LONGTEXT [not null]
  "bcc_email_22" LONGTEXT [not null]
  "content_220" LONGTEXT [not null]
  "content_221" LONGTEXT [not null]
  "subject_23" LONGTEXT [not null]
  "from_name_23" LONGTEXT [not null]
  "from_email_23" LONGTEXT [not null]
  "to_name_23" LONGTEXT [not null]
  "to_email_23" LONGTEXT [not null]
  "cc_name_23" LONGTEXT [not null]
  "cc_email_23" LONGTEXT [not null]
  "bcc_name_23" LONGTEXT [not null]
  "bcc_email_23" LONGTEXT [not null]
  "content_230" LONGTEXT [not null]
  "content_231" LONGTEXT [not null]
  "subject_24" LONGTEXT [not null]
  "from_name_24" LONGTEXT [not null]
  "from_email_24" LONGTEXT [not null]
  "to_name_24" LONGTEXT [not null]
  "to_email_24" LONGTEXT [not null]
  "cc_name_24" LONGTEXT [not null]
  "cc_email_24" LONGTEXT [not null]
  "bcc_name_24" LONGTEXT [not null]
  "bcc_email_24" LONGTEXT [not null]
  "content_240" LONGTEXT [not null]
  "content_241" LONGTEXT [not null]
  "subject_25" LONGTEXT [not null]
  "from_name_25" LONGTEXT [not null]
  "from_email_25" LONGTEXT [not null]
  "to_name_25" LONGTEXT [not null]
  "to_email_25" LONGTEXT [not null]
  "cc_name_25" LONGTEXT [not null]
  "cc_email_25" LONGTEXT [not null]
  "bcc_name_25" LONGTEXT [not null]
  "bcc_email_25" LONGTEXT [not null]
  "content_250" LONGTEXT [not null]
  "content_251" LONGTEXT [not null]
  "subject_26" LONGTEXT [not null]
  "from_name_26" LONGTEXT [not null]
  "from_email_26" LONGTEXT [not null]
  "to_name_26" LONGTEXT [not null]
  "to_email_26" LONGTEXT [not null]
  "cc_name_26" LONGTEXT [not null]
  "cc_email_26" LONGTEXT [not null]
  "bcc_name_26" LONGTEXT [not null]
  "bcc_email_26" LONGTEXT [not null]
  "content_260" LONGTEXT [not null]
  "content_261" LONGTEXT [not null]
  "subject_27" LONGTEXT [not null]
  "from_name_27" LONGTEXT [not null]
  "from_email_27" LONGTEXT [not null]
  "to_name_27" LONGTEXT [not null]
  "to_email_27" LONGTEXT [not null]
  "cc_name_27" LONGTEXT [not null]
  "cc_email_27" LONGTEXT [not null]
  "bcc_name_27" LONGTEXT [not null]
  "bcc_email_27" LONGTEXT [not null]
  "content_270" LONGTEXT [not null]
  "content_271" LONGTEXT [not null]
}

Table "membership" {
  "id" TINYINT(4) [pk, not null]
  "name" VARCHAR(50) [default: NULL]
  "equity" DOUBLE [default: NULL]
  "multiplier" DOUBLE [default: NULL]
}

Table "mrg_migrations" {
  "id" INT(11) [pk, not null, increment]
  "timestamp" BIGINT(20) [not null]
  "name" VARCHAR(255) [not null]
}

Table "mrg_queue" {
  "id" INT(11) [pk, not null, increment]
  "category" VARCHAR(18) [not null]
  "task" VARCHAR(64) [not null]
  "params" TEXT [default: NULL]
  "locked_id" VARCHAR(64) [default: NULL]
  "priority" INT(11) [not null, default: "10"]
  "retry" INT(11) [not null, default: "0"]
  "max_retry" INT(11) [not null, default: "0"]
  "last_retry" DATETIME [default: NULL]
  "created_at" DATETIME [default: `utc_timestamp()`]
  "available_at" DATETIME [default: NULL]
  "expired_at" DATETIME [default: NULL]
  "last_message" TEXT [default: NULL]

Indexes {
  category [name: "category"]
  task [name: "task"]
  priority [name: "priority"]
  available_at [name: "available_at"]
  expired_at [name: "expired_at"]
  locked_id [name: "locked_id"]
}
}

Table "mrg_whitelabel_manager_access" {
  "id" INT(11) [pk, not null, increment]
  "manager_id" INT(11) [not null]
  "company_id" INT(11) [not null]

Indexes {
  (manager_id, company_id) [unique, name: "manager_id_company_id"]
  manager_id [name: "manager_id"]
  company_id [name: "company_id"]
}
}

Table "mrg_whitelabel_manager" {
  "id" INT(11) [pk, not null, increment]
  "name" VARCHAR(50) [not null]
  "description" VARCHAR(50) [default: NULL]
  "secret_key" VARCHAR(96) [not null, default: "0"]
  "private_jwt_key" MEDIUMTEXT [default: NULL]
  "public_jwt_key" MEDIUMTEXT [default: NULL]

Indexes {
  secret_key [unique, name: "secret_key"]
}
}

Table "mrg_whitelabel" {
  "id" INT(11) [pk, not null, increment]
  "company" VARCHAR(96) [not null]
  "endpoint_url" TEXT [default: NULL]
  "additional_header" TEXT [default: NULL]
  "main_url" VARCHAR(128) [default: NULL]
  "ims_url" VARCHAR(128) [default: NULL]
  "symbol" VARCHAR(10) [not null, default: ""]

Indexes {
  company [unique, name: "mrg_whitelabel_company"]
  symbol [unique, name: "mrg_whitelabel_symbol"]
}
}

Table "mt4_users" {
  "LOGIN" INT(11) [pk, not null]
  "GROUP" CHAR(16) [not null]
  "ENABLE" INT(11) [not null]
  "ENABLE_CHANGE_PASS" INT(11) [not null]
  "ENABLE_READONLY" INT(11) [not null]
  "ENABLE_OTP" INT(11) [not null, default: "0"]
  "PASSWORD_PHONE" CHAR(32) [not null]
  "NAME" CHAR(128) [not null]
  "COUNTRY" CHAR(32) [not null]
  "CITY" CHAR(32) [not null]
  "STATE" CHAR(32) [not null]
  "ZIPCODE" CHAR(16) [not null]
  "ADDRESS" CHAR(128) [not null]
  "LEAD_SOURCE" CHAR(32) [not null, default: ""]
  "PHONE" CHAR(32) [not null]
  "EMAIL" CHAR(48) [not null]
  "COMMENT" CHAR(64) [not null]
  "ID" CHAR(32) [not null]
  "STATUS" CHAR(16) [not null]
  "REGDATE" DATETIME [not null]
  "LASTDATE" DATETIME [not null]
  "LEVERAGE" INT(11) [not null]
  "AGENT_ACCOUNT" INT(11) [not null]
  "TIMESTAMP" INT(11) [not null]
  "BALANCE" DOUBLE [not null]
  "PREVMONTHBALANCE" DOUBLE [not null]
  "PREVBALANCE" DOUBLE [not null]
  "CREDIT" DOUBLE [not null]
  "INTERESTRATE" DOUBLE [not null]
  "TAXES" DOUBLE [not null]
  "SEND_REPORTS" INT(11) [not null]
  "MQID" INT(10) [not null, default: "0"]
  "USER_COLOR" INT(11) [not null]
  "EQUITY" DOUBLE [not null, default: "0"]
  "MARGIN" DOUBLE [not null, default: "0"]
  "MARGIN_LEVEL" DOUBLE [not null, default: "0"]
  "MARGIN_FREE" DOUBLE [not null, default: "0"]
  "CURRENCY" CHAR(16) [not null, default: ""]
  "API_DATA" BLOB [default: NULL]
  "MODIFY_TIME" DATETIME [not null]
  "MRG_ID" INT(11) [default: NULL]
  "MRG_USERNAME" VARCHAR(100) [default: NULL]
  "MRG_EMAIL" VARCHAR(50) [default: NULL]
  "LAST_TRADES" DATETIME [default: NULL]
  "LAST_ACTIVITY" DATETIME [default: NULL]
  "EXPIRED" DATETIME [default: NULL]
  "MODIFY_TIMESTAMP" INT(11) [not null, default: "0"]

Indexes {
  TIMESTAMP [name: "INDEX_STAMP"]
  LAST_TRADES [name: "INDEX_LAST_TRADES"]
  GROUP [name: "INDEX_GROUP"]
  REGDATE [name: "INDEX_REGDATE"]
  EMAIL [name: "INDEX_EMAIL"]
  MRG_ID [name: "MRG_ID"]
  MRG_USERNAME [name: "MRG_USERNAME"]
  MRG_EMAIL [name: "MRG_EMAIL"]
  LAST_ACTIVITY [name: "LAST_ACTIVITY"]
  EXPIRED [name: "EXPIRED"]
  MODIFY_TIMESTAMP [name: "MODIFY_TIMESTAMP"]
}
}

Table "mt4login" {
  "id" INT(11) [pk, not null, increment]
  "mt4id" INT(11) [not null]
  "group" VARCHAR(16) [not null]
  "balance" DOUBLE [not null]
  "equity" DOUBLE [not null]
  "margin" DOUBLE [not null]
  "freemargin" DOUBLE [not null]
  "type" VARCHAR(50) [not null]
  "dt" DATETIME [not null]
  "ipclient" VARCHAR(50) [not null]
  "ip" VARCHAR(50) [not null]
}

Table "mt4reset" {
  "id" INT(11) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "1"]
  "userid" INT(11) [not null]
  "platform_id" VARCHAR(50) [not null]
  "platform" TINYINT(4) [not null, default: "0"]
  "origin" TINYINT(4) [not null, default: "0"]
  "posted" INT(11) [not null]
  "modified" INT(11) [default: NULL]
  "modifier" INT(11) [default: NULL]
  "status" TINYINT(4) [not null, default: "0", note: '0: requested 1:done']

Indexes {
  platform_id [name: "plat_id"]
  userid [name: "userid"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "mt4trades" {
  "order" INT(11) [pk, not null]
  "login" INT(11) [not null]
  "group" VARCHAR(16) [not null]
  "symbol" VARCHAR(16) [not null]
  "digits" INT(11) [not null]
  "cmd" VARCHAR(16) [not null]
  "volume" DOUBLE [not null]
  "open_time" TIMESTAMP [not null, default: `current_timestamp()`]
  "open_price" DOUBLE [not null]
  "sl" DOUBLE [not null]
  "tp" DOUBLE [not null]
  "close_time" TIMESTAMP [not null, default: "0000-00-00 00:00:00"]
  "reason" VARCHAR(16) [not null]
  "commission" DOUBLE [not null]
  "commission_agent" DOUBLE [not null]
  "swap" DOUBLE [not null]
  "close_price" DOUBLE [not null]
  "profit" DOUBLE [not null]
  "taxes" DOUBLE [not null]
  "comment" VARCHAR(32) [not null]
}

Table "nocan" {
  "idx_nocan" INT(11) [pk, not null, increment]
  "nocan" INT(11) [not null]
  "user_id" VARCHAR(11) [not null]
  "sold" VARCHAR(1) [not null]
  "sold_date" INT(11) [not null]

Indexes {
  nocan [unique, name: "nocan"]
}
}

Table "open_account_ctrader" {
  "id" BIGINT(20) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platform_id" VARCHAR(20) [not null]
  "tipe" INT(1) [not null, default: "0"]
  "req_time" INT(10) [not null]
  "create_time" INT(10) [not null, default: "0"]
  "contest" INT(1) [not null, default: "0"]
  "acc_type" INT(1) [not null, default: "0"]
  "origin" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
  platform_id [name: "platform_id"]
}
}

Table "open_account_inactive" {
  "id" BIGINT(20) [not null, default: "0"]
  "metaserver_id" INT(11) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "platform_id" VARCHAR(20) [not null, default: ""]
  "tipe" INT(1) [not null, default: "0"]
  "current_group" VARCHAR(64) [default: NULL]
  "req_time" INT(10) [not null, default: "0"]
  "create_time" INT(10) [not null, default: "0"]
  "contest" INT(1) [not null, default: "0"]
  "acc_type" INT(1) [not null, default: "0"]
  "origin" TINYINT(1) [not null, default: "0"]
  "ct" VARCHAR(20) [default: NULL]
  "lastActivity" DATETIME [default: NULL]
  "lastTrade" DATETIME [default: NULL]
  "expired" DATETIME [default: NULL]
  "cashback" TINYINT(4) [not null, default: "0"]
  "last_balance" DOUBLE [not null, default: "0"]
  "last_equity" DOUBLE [not null, default: "0"]
  "last_margin_level" DOUBLE [not null, default: "0"]
  "last_margin_update" DATETIME [default: NULL]
  "first_depo" DOUBLE [not null, default: "0"]
  "first_depo_idr" DOUBLE [not null, default: "0"]
  "first_depo_tm" DATETIME [default: NULL]
  "first_depo_verifier" INT(11) [default: NULL]
  "first_depo_verify_tm" DATETIME [default: NULL]
  "total_lot" DOUBLE [not null, default: "0"]
  "total_lot_last_count" DATETIME [default: NULL]
  "total_lot_cur_month" DOUBLE [not null, default: "0"]
  "total_profit_cur_month" DOUBLE [not null, default: "0"]
  "total_lot_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_cur_month" DOUBLE [not null, default: "0"]
  "total_mi_cur_month" DOUBLE [not null, default: "0"]
  "total_mo_cur_month" DOUBLE [not null, default: "0"]
  "total_nmi_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_last_month" DOUBLE [not null, default: "0"]
  "total_mi_last_month" DOUBLE [not null, default: "0"]
  "total_mo_last_month" DOUBLE [not null, default: "0"]
  "total_nmi_last_3months" DOUBLE [not null, default: "0"]
  "total_mi_last_3months" DOUBLE [not null, default: "0"]
  "total_mo_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_last_month" DOUBLE [not null, default: "0"]
  "total_profit_last_month" DOUBLE [not null, default: "0"]
  "total_lot_last_3months" DOUBLE [not null, default: "0"]
  "total_profit_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_monthly_last_count" DATETIME [default: NULL]
  "total_nmi_monthly_last_count" DATETIME [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  first_depo_tm [name: "first_depo_tm"]
  first_depo [name: "first_depo"]
  total_lot [name: "total_lot"]
  total_lot_last_count [name: "total_lot_last_count"]
  cashback [name: "cashback"]
  total_lot_last_month [name: "total_lot_last_month"]
  total_nmi_last_month [name: "total_nmi_last_month"]
  total_lot_last_3months [name: "total_lot_last_3months"]
  total_nmi_last_3months [name: "total_nmi_last_3months"]
  total_lot_cur_month [name: "total_lot_cur_month"]
  total_nmi_cur_month [name: "total_nmi_cur_month"]
  total_lot_cur_month_last_count [name: "total_lot_cur_month_last_count"]
  total_nmi_cur_month_last_count [name: "total_nmi_cur_month_last_count"]
  total_profit_cur_month [name: "total_profit_cur_month"]
  total_mi_cur_month [name: "total_mi_cur_month"]
  total_mo_cur_month [name: "total_mo_cur_month"]
  total_mi_last_month [name: "total_mi_last_month"]
  total_mo_last_month [name: "total_mo_last_month"]
  total_mi_last_3months [name: "total_mi_last_3months"]
  total_mo_last_3months [name: "total_mo_last_3months"]
  total_profit_last_month [name: "total_profit_last_month"]
  total_profit_last_3months [name: "total_profit_last_3months"]
  total_lot_monthly_last_count [name: "total_lot_monthly_last_count"]
  total_nmi_monthly_last_count [name: "total_nmi_monthly_last_count"]
  last_balance [name: "last_balance"]
  last_equity [name: "last_equity"]
  last_margin_level [name: "last_margin_level"]
  first_depo_verifier [name: "first_depo_verifier"]
  first_depo_idr [name: "first_depo_idr"]
  first_depo_verify_tm [name: "first_depo_verify_tm"]
  current_group [name: "current_group"]
  last_margin_update [name: "last_margin_update"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "open_account_x" {
  "id" BIGINT(20) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "platform_id" VARCHAR(20) [not null]
  "tipe" INT(1) [not null, default: "0"]
  "req_time" INT(10) [not null]
  "create_time" INT(10) [not null, default: "0"]
  "contest" INT(1) [not null, default: "0"]
  "acc_type" INT(1) [not null, default: "0"]
  "origin" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
  platform_id [name: "platform_id"]
}
}

Table "open_account" {
  "id" BIGINT(20) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "platform_id" VARCHAR(20) [not null, default: ""]
  "tipe" INT(1) [not null, default: "0", note: '0=MT4\r\n1=cTrader\r\n2=Gwazy']
  "current_group" VARCHAR(64) [default: NULL]
  "req_time" INT(10) [not null, default: "0"]
  "create_time" INT(10) [not null, default: "0"]
  "contest" INT(1) [not null, default: "0", note: '0=Contest\r\n1=Not Contest']
  "acc_type" INT(1) [not null, default: "0", note: '0=Premium\r\n1=Syariah\r\n2=Basic\r\n3=Forexadana\r\n4=ProTrader\r\n5=Infinite\r\n']
  "origin" TINYINT(1) [not null, default: "0", note: '0=IMS MRG Indo\r\n1=IMS MRG Inter']
  "ct" VARCHAR(20) [default: NULL]
  "lastActivity" DATETIME [default: NULL]
  "lastTrade" DATETIME [default: NULL]
  "expired" DATETIME [default: NULL]
  "cashback" TINYINT(4) [not null, default: "0"]
  "last_balance" DOUBLE [not null, default: "0"]
  "last_equity" DOUBLE [not null, default: "0"]
  "last_margin_level" DOUBLE [not null, default: "0"]
  "last_margin_update" DATETIME [default: NULL]
  "first_depo" DOUBLE [not null, default: "0"]
  "first_depo_idr" DOUBLE [not null, default: "0"]
  "first_depo_tm" DATETIME [default: NULL]
  "first_depo_verifier" INT(11) [default: NULL]
  "first_depo_verify_tm" DATETIME [default: NULL]
  "total_lot" DOUBLE [not null, default: "0"]
  "total_lot_last_count" DATETIME [default: NULL]
  "total_lot_cur_month" DOUBLE [not null, default: "0"]
  "total_profit_cur_month" DOUBLE [not null, default: "0"]
  "total_lot_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_cur_month" DOUBLE [not null, default: "0"]
  "total_mi_cur_month" DOUBLE [not null, default: "0"]
  "total_mo_cur_month" DOUBLE [not null, default: "0"]
  "total_nmi_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_last_month" DOUBLE [not null, default: "0"]
  "total_mi_last_month" DOUBLE [not null, default: "0"]
  "total_mo_last_month" DOUBLE [not null, default: "0"]
  "total_nmi_last_3months" DOUBLE [not null, default: "0"]
  "total_mi_last_3months" DOUBLE [not null, default: "0"]
  "total_mo_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_last_month" DOUBLE [not null, default: "0"]
  "total_profit_last_month" DOUBLE [not null, default: "0"]
  "total_lot_last_3months" DOUBLE [not null, default: "0"]
  "total_profit_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_monthly_last_count" DATETIME [default: NULL]
  "total_nmi_monthly_last_count" DATETIME [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
  platform_id [name: "platform_id"]
  lastActivity [name: "lastActivity"]
  expired [name: "expired"]
  lastTrade [name: "lastTrade"]
  first_depo_tm [name: "first_depo_tm"]
  first_depo [name: "first_depo"]
  total_lot [name: "total_lot"]
  total_lot_last_count [name: "total_lot_last_count"]
  cashback [name: "cashback"]
  total_lot_last_month [name: "total_lot_last_month"]
  total_nmi_last_month [name: "total_nmi_last_month"]
  total_lot_last_3months [name: "total_lot_last_3months"]
  total_nmi_last_3months [name: "total_nmi_last_3months"]
  total_lot_cur_month [name: "total_lot_cur_month"]
  total_nmi_cur_month [name: "total_nmi_cur_month"]
  total_lot_cur_month_last_count [name: "total_lot_cur_month_last_count"]
  total_nmi_cur_month_last_count [name: "total_nmi_cur_month_last_count"]
  total_profit_cur_month [name: "total_profit_cur_month"]
  total_mi_cur_month [name: "total_mi_cur_month"]
  total_mo_cur_month [name: "total_mo_cur_month"]
  total_mi_last_month [name: "total_mi_last_month"]
  total_mo_last_month [name: "total_mo_last_month"]
  total_mi_last_3months [name: "total_mi_last_3months"]
  total_mo_last_3months [name: "total_mo_last_3months"]
  total_profit_last_month [name: "total_profit_last_month"]
  total_profit_last_3months [name: "total_profit_last_3months"]
  total_lot_monthly_last_count [name: "total_lot_monthly_last_count"]
  total_nmi_monthly_last_count [name: "total_nmi_monthly_last_count"]
  last_balance [name: "last_balance"]
  last_equity [name: "last_equity"]
  last_margin_level [name: "last_margin_level"]
  first_depo_verifier [name: "first_depo_verifier"]
  first_depo_idr [name: "first_depo_idr"]
  first_depo_verify_tm [name: "first_depo_verify_tm"]
  current_group [name: "current_group"]
  last_margin_update [name: "last_margin_update"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "point_users" {
  "id" INT(10) [pk, not null, increment]
  "userid" INT(10) [not null]
  "membership" TINYINT(3) [not null, default: "0"]
  "nominal" INT(10) [not null]
  "expired" INT(10) [not null]
  "posted" INT(10) [not null]
  "admin" INT(10) [not null, note: 'user who posted']
  "reason" TEXT [default: NULL]
  "sisa" INT(11) [not null]
  "rate" INT(11) [default: NULL]
  "params" TEXT [default: NULL]

Indexes {
  admin [name: "admin"]
  userid [name: "Index 3"]
}
}

Table "point" {
  "id" INT(10) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "1"]
  "platform_id" VARCHAR(50) [not null]
  "group" VARCHAR(100) [not null]
  "lot" FLOAT [not null]
  "membership" TINYINT(3) [not null]
  "nominal" INT(10) [not null]
  "expired" INT(10) [not null]
  "posted" INT(10) [not null]
  "admin" INT(10) [not null, note: 'user who posted']
  "reason" TEXT [default: NULL]
  "sisa" INT(11) [not null]
  "rate" INT(11) [default: NULL]

Indexes {
  platform_id [name: "account"]
  admin [name: "admin"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "real_contest_2016_inactive" {
  "id" INT(11) [pk, not null, default: "0"]
  "user_id" INT(5) [not null]
  "user_mt4id" INT(15) [not null]
  "password" VARCHAR(8) [not null]
  "time" INT(10) [not null]
  "active" TINYINT(4) [not null, default: "1"]
}

Table "real_contest_2016" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "user_mt4id" INT(15) [not null]
  "password" VARCHAR(8) [not null]
  "time" INT(10) [not null]
  "active" TINYINT(4) [not null, default: "1"]

Indexes {
  time [name: "time"]
  user_id [name: "user_id"]
}
}

Table "redeem_costs" {
  "id" INT(11) [pk, not null, increment]
  "reid" INT(11) [not null]
  "label" TINYTEXT [not null]
  "costs" DOUBLE [not null]
  "desc" TEXT [default: NULL]

Indexes {
  reid [name: "Index 2"]
}
}

Table "redeem_detail" {
  "id" INT(11) [pk, not null, increment]
  "reid" INT(11) [not null]
  "nominal" INT(11) [not null]
  "point_id" INT(11) [not null]
  "source" VARCHAR(10) [not null]

Indexes {
  reid [name: "reid"]
  point_id [name: "point_id"]
}
}

Table "redeem" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(11) [not null]
  "reward_id" INT(11) [not null]
  "nominal" INT(11) [not null, note: 'total redeemed point']
  "additional" INT(11) [default: NULL, note: 'in Rp']
  "submitted" INT(11) [not null]
  "to_name" VARCHAR(50) [not null]
  "to_phone" VARCHAR(50) [not null]
  "to_address" TEXT [not null]
  "ship_code" VARCHAR(50) [default: NULL, note: 'no resi']
  "reason" TEXT [default: NULL]
  "status" TINYINT(4) [not null, default: "0", note: '0:redeemed, 1:processed, 2:on-delivery, 3:success, 4:cancel']
  "last_modify" INT(11) [not null]

Indexes {
  user_id [name: "user_id"]
  reward_id [name: "reward"]
}
}

Table "req_protrader_depo_ref" {
  "deposit_id" INT(11) [pk, not null]
  "deporef_id" INT(11) [not null]

Indexes {
  deporef_id [unique, name: "deporef_id"]
}
}

Table "req_protrader_depo" {
  "id" INT(11) [pk, not null, increment]
  "nominal" DECIMAL(15,2) [not null, default: "0.00"]
  "status" TINYINT(4) [not null, default: "1", note: '0: disabled; 1: active']
}

Table "req_protrader" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(11) [not null]
  "phone" VARCHAR(100) [not null]
  "address" TEXT [not null]
  "broker_name" TEXT [not null]
  "mt4_id" TEXT [not null]
  "inv_pass" TEXT [not null]
  "deposit" TINYINT(4) [not null]
  "status" TINYINT(4) [not null, default: "0", note: '0: onprogress; 1: success; 2: rejected; 3: upload ID failed ']
  "req_date" BIGINT(20) [not null]
  "open_acc_id" INT(11) [default: NULL]
  "active_date" BIGINT(20) [default: NULL]
  "expired_date" BIGINT(20) [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null]
  Note: 'Untuk menampung request Open Account Pro Trader'
}

Table "rewards_category" {
  "id" INT(11) [pk, not null, increment]
  "name" VARCHAR(50) [not null]

Indexes {
  name [unique, name: "name"]
}
}

Table "rewards_tour" {
  "id" INT(11) [pk, not null, increment]
  "point" INT(11) [not null]
  "silver" INT(11) [not null]
  "gold" INT(11) [not null]
  "platinum" INT(11) [not null]
  "diamond" INT(11) [not null]
}

Table "rewards_whitelabel" {
  "id" INT(11) [pk, not null, increment]
  "reward_id" INT(11) [not null]
  "company" INT(11) [not null]

Indexes {
  (reward_id, company) [unique, name: "reward_company"]
  company [name: "company"]
  reward_id [name: "reward_id"]
}
}

Table "rewards" {
  "id" INT(11) [pk, not null, increment]
  "category" INT(11) [not null]
  "name" VARCHAR(50) [not null]
  "description" TEXT [default: NULL]
  "stock" INT(11) [not null, default: `-1`, note: '-1: unlimited']
  "expired" INT(11) [default: NULL]
  "nominal" INT(11) [not null]
  "product" VARCHAR(50) [default: NULL]
  "sticky" TINYINT(4) [default: NULL]
  "featured" TINYINT(4) [default: NULL]
  "status" TINYINT(4) [not null, default: "0"]
  "params" TEXT [default: NULL]
}

Table "search_log" {
  "id" INT(10) [pk, not null, increment]
  "query" LONGTEXT [not null]
}


Table "test_table" {
  "id" INT(11) [pk, not null, increment]
  "name" VARCHAR(50) [not null, default: "0"]
  "MODIFIED_AT" INT(11) [not null, default: "0"]
}

Table "ticket_conv" {
  "id" INT(11) [pk, not null, increment]
  "ticket_id" INT(11) [not null, default: "0"]
  "user_id" INT(11) [not null, default: "0"]
  "message" TEXT [not null]
  "CREATED_AT" BIGINT(20) [not null]
}

Table "ticket" {
  "id" INT(11) [pk, not null, increment]
  "user_id" INT(11) [not null]
  "subject" TEXT [not null]
  "type" INT(11) [not null]
  "related_account" INT(11) [default: NULL]
  "priority" INT(11) [not null]
  "status" INT(11) [not null, default: "1", note: '0: closed, 1: open']
  "CREATED_AT" BIGINT(20) [not null]
  "MODIFIY_TIME" BIGINT(20) [not null]
}

Table "tmp" {
  "account" VARCHAR(50) [not null]

Indexes {
  account [unique, name: "email"]
}
  Note: 'buat cocokin data - Vicky'
}

Table "tools_transaction" {
  "id" INT(5) [pk, not null, increment]
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(20) [not null]
  "metaserver_id" INT(11) [not null, default: "1"]
  "manager" VARCHAR(20) [not null]
  "ref_number" VARCHAR(50) [not null]
  "link" INT(11) [default: NULL]
  "nominal" DECIMAL(15,6) [not null]
  "rate" DECIMAL(10,2) [default: NULL]
  "time" INT(10) [not null]
  "tipe" INT(11) [not null, note: '0=deposit; 1=depositInternal; 1000=withdraw; 1001=withdrawInternal; 2000=newAccount; 3000=rebate; 3001=cashback;']
  "comment" VARCHAR(200) [not null]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  ref_number [unique, name: "ref_number"]
  mt4id [name: "mt4id"]
  user_id [name: "user_id"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "trash_users" {
  "user_id" INT(5) [not null]
  "user_level" INT(1) [not null, default: "1"]
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(25) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_birth" DATE [not null, default: "0000-00-00"]
  "user_blntgl" VARCHAR(4) [not null, default: "0000"]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null]
  "user_mt4id" VARCHAR(255) [not null]
  "user_bbpin" VARCHAR(10) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "user_registered" INT(10) [not null]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_marketing_id" INT(11) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [not null]
  "real_acc" INT(1) [not null, default: "0"]
  "euro2012" INT(1) [not null, default: "0"]
  "country" VARCHAR(2) [not null, default: "id"]
  "city" VARCHAR(50) [not null]
  "paypal" VARCHAR(50) [not null]
  "origin" TINYINT(1) [not null, default: "0"]
  "subscribe" TINYINT(1) [not null, default: "1"]
  "email_ver" TINYINT(1) [not null, default: "1"]
  "first_visit" VARCHAR(255) [not null]
  "goal_visit" VARCHAR(255) [not null]
  "goal_referrer" VARCHAR(255) [not null]
}

Table "users_city" {
  "userid" INT(5) [pk, not null]
  "ket" VARCHAR(50) [default: NULL]
  Note: 'userid yang city nya tidak ditemukan gmaps'
}

Table "users_demoid" {
  "idx" INT(11) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "user_demoid" VARCHAR(21) [default: NULL]
  "password" VARCHAR(20) [not null]
  "reqtime" INT(10) [not null]
  "createtime" INT(10) [not null]
  "platform" TINYINT(1) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
  metaserver_id [name: "metaserver_id"]
}
}

Table "users_dynamic" {
  "userid" INT(11) [not null]
  "event" INT(11) [not null]
  "creator" INT(11) [not null]
}

Table "users_error" {
  "source" INT(11) [not null]
  "LOGIN" INT(11) [default: NULL]
  "NAME" CHAR(128) [default: NULL]
  "PHONE" CHAR(32) [default: NULL]
  "EMAIL" CHAR(48) [default: NULL]
  Note: 'request Adi - 23/12/2016'
}

Table "users_from_tf" {
  "registered" INT(11) [not null]
  "email" VARCHAR(50) [pk, not null]
  "first_referrer" VARCHAR(200) [not null]
  "goal_referrer" VARCHAR(200) [not null]
  Note: 'data user dari IMS TF utk join ke MRG'
}

Table "users_groups_rules" {
  "group_id" INT(11) [not null]
  "rules_id" INT(11) [not null]

Indexes {
  (group_id, rules_id) [pk]
}
}

Table "users_groups" {
  "id" INT(11) [pk, not null, increment]
  "path" TEXT [not null]
  "groupname" VARCHAR(40) [not null]
}

Table "users_mt4id" {
  "user_id" INT(5) [not null]
  "user_mt4id" VARCHAR(20) [pk, not null, default: ""]
  "rate" INT(1) [not null]
  "id_created" INT(10) [not null]

Indexes {
  user_id [name: "user_id"]
}
}

Table "users_rules" {
  "id" INT(11) [pk, not null]
  "rules" VARCHAR(128) [not null]
  "state" TINYINT(4) [not null, default: "0"]

Indexes {
  rules [unique, name: "rules"]
  state [name: "state"]
}
}

Table "users" {
  "user_id" INT(5) [pk, not null, increment]
  "user_company" INT(11) [not null, default: "0"]
  "user_level" INT(1) [not null, default: "1", note: '1=Investor\r\n2=Affiliate\r\n3=Admin\r\n4=Cashier\r\n5=IB\r\n6=Marketing\r\n7=Livechat']
  "user_name" VARCHAR(100) [default: NULL]
  "user_pass" VARCHAR(25) [default: NULL]
  "user_email" VARCHAR(50) [default: NULL]
  "user_realname" VARCHAR(100) [not null, default: ""]
  "user_birth" DATE [not null, default: "0000-00-00"]
  "user_blntgl" VARCHAR(4) [not null, default: "0000"]
  "user_addr" VARCHAR(255) [not null, default: ""]
  "user_phone" VARCHAR(15) [not null, default: ""]
  "user_mobile" VARCHAR(15) [not null, default: ""]
  "user_mt4id" VARCHAR(255) [not null, default: ""]
  "user_bbpin" VARCHAR(10) [not null, default: ""]
  "user_bankname" VARCHAR(20) [not null, default: ""]
  "user_bankaccno" VARCHAR(20) [not null, default: ""]
  "user_bankreg" VARCHAR(100) [not null, default: ""]
  "user_registered" INT(10) [not null, default: "0"]
  "user_referrer_id" INT(5) [not null, default: "0"]
  "user_marketing_id" INT(11) [not null, default: "0"]
  "user_ref_url" VARCHAR(255) [default: NULL]
  "real_acc" INT(1) [not null, default: "0"]
  "euro2012" INT(1) [not null, default: "0"]
  "country" VARCHAR(2) [not null, default: "id"]
  "city" VARCHAR(50) [not null, default: ""]
  "paypal" VARCHAR(50) [default: NULL]
  "origin" TINYINT(1) [not null, default: "0"]
  "subscribe" TINYINT(1) [not null, default: "1"]
  "email_ver" TINYINT(1) [not null, default: "0"]
  "first_visit" VARCHAR(255) [default: NULL]
  "last_visit" VARCHAR(128) [default: NULL]
  "need_update_fv" TINYINT(1) [not null, default: "0"]
  "utm_campaign" VARCHAR(128) [default: NULL]
  "utm_source" VARCHAR(128) [default: NULL]
  "utm_medium" VARCHAR(128) [default: NULL]
  "utm_term" VARCHAR(128) [default: NULL]
  "campaignid" VARCHAR(128) [default: NULL]
  "adgroupid" VARCHAR(128) [default: NULL]
  "adid" VARCHAR(128) [default: NULL]
  "gclid" VARCHAR(255) [default: NULL]
  "need_update_ref" TINYINT(1) [not null, default: "0"]
  "last_utm_campaign" VARCHAR(128) [default: NULL]
  "last_utm_source" VARCHAR(128) [default: NULL]
  "last_utm_medium" VARCHAR(128) [default: NULL]
  "last_utm_term" VARCHAR(128) [default: NULL]
  "last_campaignid" VARCHAR(128) [default: NULL]
  "last_adgroupid" VARCHAR(128) [default: NULL]
  "last_adid" VARCHAR(128) [default: NULL]
  "last_gclid" VARCHAR(255) [default: NULL]
  "goal_visit" VARCHAR(255) [default: NULL]
  "goal_referrer" VARCHAR(255) [default: NULL]
  "affiliate_date" INT(10) [default: NULL]
  "affpath" TEXT [default: NULL]
  "membership" TINYINT(4) [not null, default: "0"]
  "best" TINYINT(4) [not null, default: "0"]
  "change_bank" TINYINT(4) [not null, default: "0", note: '0: No (Default), 1: One time only, 2: Permanent']
  "block_wd" TINYINT(4) [not null, default: "0"]
  "first_depo" DOUBLE [not null, default: "0"]
  "first_depo_tm" DATETIME [default: NULL]
  "total_lot" DOUBLE [not null, default: "0"]
  "total_lot_last_count" DATETIME [default: NULL]
  "total_lot_cur_month" DOUBLE [not null, default: "0"]
  "total_profit_cur_month" DOUBLE [not null, default: "0"]
  "total_lot_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_cur_month" DOUBLE [not null, default: "0"]
  "total_mi_cur_month" DOUBLE [not null, default: "0"]
  "total_mo_cur_month" DOUBLE [not null, default: "0"]
  "total_nmi_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_last_month" DOUBLE [not null, default: "0"]
  "total_mi_last_month" DOUBLE [not null, default: "0"]
  "total_mo_last_month" DOUBLE [not null, default: "0"]
  "total_nmi_last_3months" DOUBLE [not null, default: "0"]
  "total_mi_last_3months" DOUBLE [not null, default: "0"]
  "total_mo_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_last_month" DOUBLE [not null, default: "0"]
  "total_profit_last_month" DOUBLE [not null, default: "0"]
  "total_lot_last_3months" DOUBLE [not null, default: "0"]
  "total_profit_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_monthly_last_count" DATETIME [default: NULL]
  "total_nmi_monthly_last_count" DATETIME [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  user_name [unique, name: "user_name"]
  user_referrer_id [name: "user_referrer_id"]
  user_registered [name: "user_registered"]
  country [name: "country"]
  user_email [name: "user_email"]
  user_company [name: "users_user_company"]
  first_depo_tm [name: "first_depo_tm"]
  first_depo [name: "first_depo"]
  total_lot [name: "total_lot"]
  total_lot_last_count [name: "total_lot_last_count"]
  total_lot_last_month [name: "users_total_lot_last_month"]
  total_nmi_last_month [name: "users_total_nmi_last_month"]
  total_lot_last_3months [name: "users_total_lot_last_3months"]
  total_nmi_last_3months [name: "users_total_nmi_last_3months"]
  total_lot_cur_month [name: "total_lot_cur_month"]
  total_nmi_cur_month [name: "total_nmi_cur_month"]
  total_lot_cur_month_last_count [name: "total_lot_cur_month_last_count"]
  total_nmi_cur_month_last_count [name: "total_nmi_cur_month_last_count"]
  total_profit_cur_month [name: "total_profit_cur_month"]
  total_mi_cur_month [name: "total_mi_cur_month"]
  total_mo_cur_month [name: "total_mo_cur_month"]
  total_mi_last_month [name: "total_mi_last_month"]
  total_mo_last_month [name: "total_mo_last_month"]
  total_mi_last_3months [name: "total_mi_last_3months"]
  total_mo_last_3months [name: "total_mo_last_3months"]
  total_profit_last_month [name: "total_profit_last_month"]
  total_profit_last_3months [name: "total_profit_last_3months"]
  total_lot_monthly_last_count [name: "total_lot_monthly_last_count"]
  total_nmi_monthly_last_count [name: "total_nmi_monthly_last_count"]
  email_ver [name: "email_ver"]
  first_visit [name: "first_visit"]
  goal_visit [name: "goal_visit"]
  goal_referrer [name: "goal_referrer"]
  city [name: "city"]
  user_marketing_id [name: "user_marketing_id"]
  user_mobile [name: "user_mobile"]
  user_phone [name: "user_phone"]
  user_addr [name: "user_addr"]
  user_mt4id [name: "user_mt4id"]
  subscribe [name: "subscribe"]
  real_acc [name: "real_acc"]
  membership [name: "membership"]
  last_visit [name: "last_visit"]
  need_update_fv [name: "need_update_fv"]
  utm_campaign [name: "utm_campaign"]
  utm_source [name: "utm_source"]
  utm_medium [name: "utm_medium"]
  utm_term [name: "utm_term"]
  campaignid [name: "campaignid"]
  adgroupid [name: "adgroupid"]
  adid [name: "adid"]
  gclid [name: "gclid"]
  need_update_ref [name: "need_update_ref"]
  last_utm_campaign [name: "last_utm_campaign"]
  last_utm_source [name: "last_utm_source"]
  last_utm_medium [name: "last_utm_medium"]
  last_utm_term [name: "last_utm_term"]
  last_campaignid [name: "last_campaignid"]
  last_adgroupid [name: "last_adgroupid"]
  last_adid [name: "last_adid"]
  last_gclid [name: "last_gclid"]
}
}

Table "withdrawal_state" {
  "withdraw_id" INT(11) [pk, not null]
  "cashier" INT(11) [default: NULL]
  "cashier_transfer_tm" DATETIME [default: NULL]
  "cashier_note" TEXT [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_order_num" INT(11) [default: NULL]
  "settle_order_tm" DATETIME [default: NULL]
  "settle_note" TEXT [default: NULL]
  "last_modify" DATETIME [default: NULL]
}

Table "withdrawal" {
  "id" INT(5) [pk, not null, increment]
  "metaserver_id" INT(10) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(20) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "ref_number" VARCHAR(50) [default: ""]
  "nominal" DECIMAL(15,2) [not null]
  "rate" INT(1) [not null, default: "1", note: '1=fixed;2=float']
  "rateval" INT(11) [not null, default: "10000"]
  "time" INT(10) [not null]
  "tipe" INT(11) [not null, default: "2"]
  "status" INT(1) [not null, default: "0", note: '0=pending,1=verified,2=declined']
  "platform" INT(1) [not null, default: "0"]
  "paypal" VARCHAR(50) [default: ""]
  "fee" FLOAT [default: NULL]
  "origin" TINYINT(1) [not null, default: "0"]
  "fxdana" TINYINT(1) [default: NULL, note: '0=pending,1=verified,2=declined']
  "cashier" INT(11) [default: NULL]
  "cashier_complete_tm" DATETIME [default: NULL]
  "cashier_note" TEXT [default: NULL]
  "amount" DOUBLE [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_order_num" INT(11) [default: NULL]
  "settle_order_tm" DATETIME [default: NULL]
  "settle_note" TEXT [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]
  "campaignid" VARCHAR(128) [default: NULL]
  "adid" VARCHAR(128) [default: NULL]

Indexes {
  mt4id [name: "mt4id"]
  user_id [name: "user_id"]
  metaserver_id [name: "metaserver_id"]
  campaignid [name: "campaignid"]
  adid [name: "adid"]
}
}




