Table "cash_mt4_account_type" {
  "id" INT(11) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "0"]
  "platform_type" INT(11) [not null]
  "platform_name" VARCHAR(16) [not null, default: ""]
  "type_id" INT(11) [not null]
  "type_name" VARCHAR(50) [not null]
  "company" INT(11) [not null]
  "group_creation" VARCHAR(50) [default: NULL]
  "leverage" INT(11) [default: NULL]
  "min_account_num" INT(11) [default: NULL]
  "max_account_num" INT(11) [default: NULL]
  "is_public" TINYINT(4) [not null, default: "0"]
  "commission" DOUBLE [default: "0"]
  "min_first_depo" DOUBLE [not null, default: "0"]
  "min_lot" DOUBLE [default: "0"]
  "max_lot" DOUBLE [not null, default: "0"]
  "spread" DOUBLE [default: "0"]
  "swap_charged" TINYINT(4) [not null, default: "0"]
  "symbol_suffix" VARCHAR(20) [default: NULL]
  "products" VARCHAR(50) [default: "All"]
  "min_po" TEXT [default: NULL]

Indexes {
  (metaserver_id, platform_type, type_id, company) [unique, name: "cmat_unique"]
  platform_name [name: "cmat_platform_name"]
  type_id [name: "cmat_type_id"]
  type_name [name: "cmat_type_name"]
  company [name: "cmat_company"]
  platform_type [name: "cmat_platform_type"]
  group_creation [name: "cmat_group"]
  metaserver_id [name: "metaserver_id"]
}
}
