Table "deposit" {
  "id" INT(10) [pk, not null, increment]
  "metaserver_id" INT(10) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(20) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "ref_number" VARCHAR(50) [default: ""]
  "nominal" DECIMAL(15,2) [not null]
  "rate" INT(1) [not null, default: "0"]
  "rateval" INT(6) [not null, default: "100000"]
  "fg_bankname" VARCHAR(20) [not null]
  "fg_bankaccno" VARCHAR(20) [not null]
  "fg_bankreg" VARCHAR(100) [not null]
  "time" INT(10) [not null]
  "tipe" INT(1) [not null]
  "status" INT(1) [not null, default: "0"]
  "platform" INT(1) [not null, default: "0"]
  "acc_type" INT(1) [not null, default: "0"]
  "paypal" VARCHAR(50) [default: ""]
  "fee" FLOAT [not null, default: "0"]
  "origin" TINYINT(1) [not null, default: "0"]
  "fxdana" TINYINT(1) [default: NULL, note: '7: ?']
  "method" VARCHAR(50) [default: NULL]
  "method_other" VARCHAR(50) [default: NULL]
  "cashier" INT(11) [default: NULL]
  "cashier_approval" TINYINT(4) [default: NULL]
  "cashier_approval_tm" DATETIME [default: NULL]
  "cashier_note" TEXT [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_order_num" INT(11) [default: NULL]
  "settle_order_tm" DATETIME [default: NULL]
  "settle_note" TEXT [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]
  "campaignid" VARCHAR(128) [default: NULL]
  "adid" VARCHAR(128) [default: NULL]

Indexes {
  user_id [name: "user_id"]
  mt4id [name: "mt4id"]
  status [name: "status"]
  metaserver_id [name: "metaserver_id"]
  campaignid [name: "campaignid"]
  adid [name: "adid"]
}
}
