Table "email" {
  "id" INT(11) [pk, not null, increment]
  "content_id" INT(11) [not null]
  "subject" TEXT [not null]
  "from_name" TEXT [not null]
  "from_email" TEXT [not null]
  "to_name" TEXT [not null]
  "to_email" TEXT [not null]
  "cc_name" TEXT [not null]
  "cc_email" TEXT [not null]
  "bcc_name" TEXT [not null]
  "bcc_email" TEXT [not null]
  "lang" INT(11) [not null, default: "0", note: '0: Indonesia, 1: English']
  "smtp_host" TEXT [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null, default: "0"]
  "email" TEXT [not null]
  "password" TEXT [default: NULL]
}
