Table "mail" {
  "subject_0" LONGTEXT [not null]
  "from_name_0" LONGTEXT [not null]
  "from_email_0" LONGTEXT [not null]
  "to_name_0" LONGTEXT [not null]
  "to_email_0" LONGTEXT [not null]
  "cc_name_0" LONGTEXT [not null]
  "cc_email_0" LONGTEXT [not null]
  "bcc_name_0" LONGTEXT [not null]
  "bcc_email_0" LONGTEXT [not null]
  "content_00" LONGTEXT [not null]
  "content_01" LONGTEXT [not null]
  "subject_1" LONGTEXT [not null]
  "from_name_1" LONGTEXT [not null]
  "from_email_1" LONGTEXT [not null]
  "to_name_1" LONGTEXT [not null]
  "to_email_1" LONGTEXT [not null]
  "cc_name_1" LONGTEXT [not null]
  "cc_email_1" LONGTEXT [not null]
  "bcc_name_1" LONGTEXT [not null]
  "bcc_email_1" LONGTEXT [not null]
  "content_10" LONGTEXT [not null]
  "content_11" LONGTEXT [not null]
  "content_12" LONGTEXT [not null]
  "content_13" LONGTEXT [not null]
  "subject_2" LONGTEXT [not null]
  "from_name_2" LONGTEXT [not null]
  "from_email_2" LONGTEXT [not null]
  "to_name_2" LONGTEXT [not null]
  "to_email_2" LONGTEXT [not null]
  "cc_name_2" LONGTEXT [not null]
  "cc_email_2" LONGTEXT [not null]
  "bcc_name_2" LONGTEXT [not null]
  "bcc_email_2" LONGTEXT [not null]
  "content_20" LONGTEXT [not null]
  "content_21" LONGTEXT [not null]
  "subject_3" LONGTEXT [not null]
  "from_name_3" LONGTEXT [not null]
  "from_email_3" LONGTEXT [not null]
  "to_name_3" LONGTEXT [not null]
  "to_email_3" LONGTEXT [not null]
  "cc_name_3" LONGTEXT [not null]
  "cc_email_3" LONGTEXT [not null]
  "bcc_name_3" LONGTEXT [not null]
  "bcc_email_3" LONGTEXT [not null]
  "content_30" LONGTEXT [not null]
  "content_31" LONGTEXT [not null]
  "subject_4" LONGTEXT [not null]
  "from_name_4" LONGTEXT [not null]
  "from_email_4" LONGTEXT [not null]
  "to_name_4" LONGTEXT [not null]
  "to_email_4" LONGTEXT [not null]
  "cc_name_4" LONGTEXT [not null]
  "cc_email_4" LONGTEXT [not null]
  "bcc_name_4" LONGTEXT [not null]
  "bcc_email_4" LONGTEXT [not null]
  "content_40" LONGTEXT [not null]
  "content_41" LONGTEXT [not null]
  "smtp_host" VARCHAR(50) [not null]
  "smtp_port" INT(5) [not null]
  "ssl" INT(1) [not null]
  "email" VARCHAR(50) [not null]
  "password" VARCHAR(50) [not null]
  "subject_6" LONGTEXT [not null]
  "from_name_6" LONGTEXT [not null]
  "from_email_6" LONGTEXT [not null]
  "to_name_6" LONGTEXT [not null]
  "to_email_6" LONGTEXT [not null]
  "cc_name_6" LONGTEXT [not null]
  "cc_email_6" LONGTEXT [not null]
  "bcc_name_6" LONGTEXT [not null]
  "bcc_email_6" LONGTEXT [not null]
  "content_60" LONGTEXT [not null]
  "content_61" LONGTEXT [not null]
  "subject_7" LONGTEXT [not null]
  "from_name_7" LONGTEXT [not null]
  "from_email_7" LONGTEXT [not null]
  "to_name_7" LONGTEXT [not null]
  "to_email_7" LONGTEXT [not null]
  "cc_name_7" LONGTEXT [not null]
  "cc_email_7" LONGTEXT [not null]
  "bcc_name_7" LONGTEXT [not null]
  "bcc_email_7" LONGTEXT [not null]
  "content_70" LONGTEXT [not null]
  "content_71" LONGTEXT [not null]
  "subject_8" LONGTEXT [not null]
  "from_name_8" LONGTEXT [not null]
  "from_email_8" LONGTEXT [not null]
  "to_name_8" LONGTEXT [not null]
  "to_email_8" LONGTEXT [not null]
  "cc_name_8" LONGTEXT [not null]
  "cc_email_8" LONGTEXT [not null]
  "bcc_name_8" LONGTEXT [not null]
  "bcc_email_8" LONGTEXT [not null]
  "content_80" LONGTEXT [not null]
  "content_81" LONGTEXT [not null]
  "subject_9" LONGTEXT [not null]
  "from_name_9" LONGTEXT [not null]
  "from_email_9" LONGTEXT [not null]
  "to_name_9" LONGTEXT [not null]
  "to_email_9" LONGTEXT [not null]
  "cc_name_9" LONGTEXT [not null]
  "cc_email_9" LONGTEXT [not null]
  "bcc_name_9" LONGTEXT [not null]
  "bcc_email_9" LONGTEXT [not null]
  "content_90" LONGTEXT [not null]
  "content_91" LONGTEXT [not null]
  "subject_10" LONGTEXT [not null]
  "from_name_10" LONGTEXT [not null]
  "from_email_10" LONGTEXT [not null]
  "to_name_10" LONGTEXT [not null]
  "to_email_10" LONGTEXT [not null]
  "cc_name_10" LONGTEXT [not null]
  "cc_email_10" LONGTEXT [not null]
  "bcc_name_10" LONGTEXT [not null]
  "bcc_email_10" LONGTEXT [not null]
  "content_100" LONGTEXT [not null]
  "content_101" LONGTEXT [not null]
  "subject_11" LONGTEXT [not null]
  "from_name_11" LONGTEXT [not null]
  "from_email_11" LONGTEXT [not null]
  "to_name_11" LONGTEXT [not null]
  "to_email_11" LONGTEXT [not null]
  "cc_name_11" LONGTEXT [not null]
  "cc_email_11" LONGTEXT [not null]
  "bcc_name_11" LONGTEXT [not null]
  "bcc_email_11" LONGTEXT [not null]
  "content_110" LONGTEXT [not null]
  "content_111" LONGTEXT [not null]
  "subject_12" LONGTEXT [not null]
  "from_name_12" LONGTEXT [not null]
  "from_email_12" LONGTEXT [not null]
  "to_name_12" LONGTEXT [not null]
  "to_email_12" LONGTEXT [not null]
  "cc_name_12" LONGTEXT [not null]
  "cc_email_12" LONGTEXT [not null]
  "bcc_name_12" LONGTEXT [not null]
  "bcc_email_12" LONGTEXT [not null]
  "content_120" LONGTEXT [not null]
  "content_121" LONGTEXT [not null]
  "subject_13" LONGTEXT [not null]
  "from_name_13" LONGTEXT [not null]
  "from_email_13" LONGTEXT [not null]
  "to_name_13" LONGTEXT [not null]
  "to_email_13" LONGTEXT [not null]
  "cc_name_13" LONGTEXT [not null]
  "cc_email_13" LONGTEXT [not null]
  "bcc_name_13" LONGTEXT [not null]
  "bcc_email_13" LONGTEXT [not null]
  "content_130" LONGTEXT [not null]
  "content_131" LONGTEXT [not null]
  "subject_14" LONGTEXT [not null]
  "from_name_14" LONGTEXT [not null]
  "from_email_14" LONGTEXT [not null]
  "to_name_14" LONGTEXT [not null]
  "to_email_14" LONGTEXT [not null]
  "cc_name_14" LONGTEXT [not null]
  "cc_email_14" LONGTEXT [not null]
  "bcc_name_14" LONGTEXT [not null]
  "bcc_email_14" LONGTEXT [not null]
  "content_140" LONGTEXT [not null]
  "content_141" LONGTEXT [not null]
  "subject_15" LONGTEXT [not null]
  "from_name_15" LONGTEXT [not null]
  "from_email_15" LONGTEXT [not null]
  "to_name_15" LONGTEXT [not null]
  "to_email_15" LONGTEXT [not null]
  "cc_name_15" LONGTEXT [not null]
  "cc_email_15" LONGTEXT [not null]
  "bcc_name_15" LONGTEXT [not null]
  "bcc_email_15" LONGTEXT [not null]
  "content_150" LONGTEXT [not null]
  "content_151" LONGTEXT [not null]
  "subject_16" LONGTEXT [not null]
  "from_name_16" LONGTEXT [not null]
  "from_email_16" LONGTEXT [not null]
  "to_name_16" LONGTEXT [not null]
  "to_email_16" LONGTEXT [not null]
  "cc_name_16" LONGTEXT [not null]
  "cc_email_16" LONGTEXT [not null]
  "bcc_name_16" LONGTEXT [not null]
  "bcc_email_16" LONGTEXT [not null]
  "content_160" LONGTEXT [not null]
  "content_161" LONGTEXT [not null]
  "subject_17" LONGTEXT [not null]
  "from_name_17" LONGTEXT [not null]
  "from_email_17" LONGTEXT [not null]
  "to_name_17" LONGTEXT [not null]
  "to_email_17" LONGTEXT [not null]
  "cc_name_17" LONGTEXT [not null]
  "cc_email_17" LONGTEXT [not null]
  "bcc_name_17" LONGTEXT [not null]
  "bcc_email_17" LONGTEXT [not null]
  "content_170" LONGTEXT [not null]
  "content_171" LONGTEXT [not null]
  "subject_18" LONGTEXT [not null]
  "from_name_18" LONGTEXT [not null]
  "from_email_18" LONGTEXT [not null]
  "to_name_18" LONGTEXT [not null]
  "to_email_18" LONGTEXT [not null]
  "cc_name_18" LONGTEXT [not null]
  "cc_email_18" LONGTEXT [not null]
  "bcc_name_18" LONGTEXT [not null]
  "bcc_email_18" LONGTEXT [not null]
  "content_180" LONGTEXT [not null]
  "content_181" LONGTEXT [not null]
  "subject_19" LONGTEXT [not null]
  "from_name_19" LONGTEXT [not null]
  "from_email_19" LONGTEXT [not null]
  "to_name_19" LONGTEXT [not null]
  "to_email_19" LONGTEXT [not null]
  "cc_name_19" LONGTEXT [not null]
  "cc_email_19" LONGTEXT [not null]
  "bcc_name_19" LONGTEXT [not null]
  "bcc_email_19" LONGTEXT [not null]
  "content_190" LONGTEXT [not null]
  "content_191" LONGTEXT [not null]
  "subject_20" LONGTEXT [not null]
  "from_name_20" LONGTEXT [not null]
  "from_email_20" LONGTEXT [not null]
  "to_name_20" LONGTEXT [not null]
  "to_email_20" LONGTEXT [not null]
  "cc_name_20" LONGTEXT [not null]
  "cc_email_20" LONGTEXT [not null]
  "bcc_name_20" LONGTEXT [not null]
  "bcc_email_20" LONGTEXT [not null]
  "content_200" LONGTEXT [not null]
  "content_201" LONGTEXT [not null]
  "subject_21" LONGTEXT [not null]
  "from_name_21" LONGTEXT [not null]
  "from_email_21" LONGTEXT [not null]
  "to_name_21" LONGTEXT [not null]
  "to_email_21" LONGTEXT [not null]
  "cc_name_21" LONGTEXT [not null]
  "cc_email_21" LONGTEXT [not null]
  "bcc_name_21" LONGTEXT [not null]
  "bcc_email_21" LONGTEXT [not null]
  "content_210" LONGTEXT [not null]
  "content_211" LONGTEXT [not null]
  "subject_22" LONGTEXT [not null]
  "from_name_22" LONGTEXT [not null]
  "from_email_22" LONGTEXT [not null]
  "to_name_22" LONGTEXT [not null]
  "to_email_22" LONGTEXT [not null]
  "cc_name_22" LONGTEXT [not null]
  "cc_email_22" LONGTEXT [not null]
  "bcc_name_22" LONGTEXT [not null]
  "bcc_email_22" LONGTEXT [not null]
  "content_220" LONGTEXT [not null]
  "content_221" LONGTEXT [not null]
  "subject_23" LONGTEXT [not null]
  "from_name_23" LONGTEXT [not null]
  "from_email_23" LONGTEXT [not null]
  "to_name_23" LONGTEXT [not null]
  "to_email_23" LONGTEXT [not null]
  "cc_name_23" LONGTEXT [not null]
  "cc_email_23" LONGTEXT [not null]
  "bcc_name_23" LONGTEXT [not null]
  "bcc_email_23" LONGTEXT [not null]
  "content_230" LONGTEXT [not null]
  "content_231" LONGTEXT [not null]
  "subject_24" LONGTEXT [not null]
  "from_name_24" LONGTEXT [not null]
  "from_email_24" LONGTEXT [not null]
  "to_name_24" LONGTEXT [not null]
  "to_email_24" LONGTEXT [not null]
  "cc_name_24" LONGTEXT [not null]
  "cc_email_24" LONGTEXT [not null]
  "bcc_name_24" LONGTEXT [not null]
  "bcc_email_24" LONGTEXT [not null]
  "content_240" LONGTEXT [not null]
  "content_241" LONGTEXT [not null]
  "subject_25" LONGTEXT [not null]
  "from_name_25" LONGTEXT [not null]
  "from_email_25" LONGTEXT [not null]
  "to_name_25" LONGTEXT [not null]
  "to_email_25" LONGTEXT [not null]
  "cc_name_25" LONGTEXT [not null]
  "cc_email_25" LONGTEXT [not null]
  "bcc_name_25" LONGTEXT [not null]
  "bcc_email_25" LONGTEXT [not null]
  "content_250" LONGTEXT [not null]
  "content_251" LONGTEXT [not null]
  "subject_26" LONGTEXT [not null]
  "from_name_26" LONGTEXT [not null]
  "from_email_26" LONGTEXT [not null]
  "to_name_26" LONGTEXT [not null]
  "to_email_26" LONGTEXT [not null]
  "cc_name_26" LONGTEXT [not null]
  "cc_email_26" LONGTEXT [not null]
  "bcc_name_26" LONGTEXT [not null]
  "bcc_email_26" LONGTEXT [not null]
  "content_260" LONGTEXT [not null]
  "content_261" LONGTEXT [not null]
  "subject_27" LONGTEXT [not null]
  "from_name_27" LONGTEXT [not null]
  "from_email_27" LONGTEXT [not null]
  "to_name_27" LONGTEXT [not null]
  "to_email_27" LONGTEXT [not null]
  "cc_name_27" LONGTEXT [not null]
  "cc_email_27" LONGTEXT [not null]
  "bcc_name_27" LONGTEXT [not null]
  "bcc_email_27" LONGTEXT [not null]
  "content_270" LONGTEXT [not null]
  "content_271" LONGTEXT [not null]
}
