Table "mt4_users" {
  "LOGIN" INT(11) [pk, not null]
  "GROUP" CHAR(16) [not null]
  "ENABLE" INT(11) [not null]
  "ENABLE_CHANGE_PASS" INT(11) [not null]
  "ENABLE_READONLY" INT(11) [not null]
  "ENABLE_OTP" INT(11) [not null, default: "0"]
  "PASSWORD_PHONE" CHAR(32) [not null]
  "NAME" CHAR(128) [not null]
  "COUNTRY" CHAR(32) [not null]
  "CITY" CHAR(32) [not null]
  "STATE" CHAR(32) [not null]
  "ZIPCODE" CHAR(16) [not null]
  "ADDRESS" CHAR(128) [not null]
  "LEAD_SOURCE" CHAR(32) [not null, default: ""]
  "PHONE" CHAR(32) [not null]
  "EMAIL" CHAR(48) [not null]
  "COMMENT" CHAR(64) [not null]
  "ID" CHAR(32) [not null]
  "STATUS" CHAR(16) [not null]
  "REGDATE" DATETIME [not null]
  "LASTDATE" DATETIME [not null]
  "LEVERAGE" INT(11) [not null]
  "AGENT_ACCOUNT" INT(11) [not null]
  "TIMESTAMP" INT(11) [not null]
  "BALANCE" DOUBLE [not null]
  "PREVMONTHBALANCE" DOUBLE [not null]
  "PREVBALANCE" DOUBLE [not null]
  "CREDIT" DOUBLE [not null]
  "INTERESTRATE" DOUBLE [not null]
  "TAXES" DOUBLE [not null]
  "SEND_REPORTS" INT(11) [not null]
  "MQID" INT(10) [not null, default: "0"]
  "USER_COLOR" INT(11) [not null]
  "EQUITY" DOUBLE [not null, default: "0"]
  "MARGIN" DOUBLE [not null, default: "0"]
  "MARGIN_LEVEL" DOUBLE [not null, default: "0"]
  "MARGIN_FREE" DOUBLE [not null, default: "0"]
  "CURRENCY" CHAR(16) [not null, default: ""]
  "API_DATA" BLOB [default: NULL]
  "MODIFY_TIME" DATETIME [not null]
  "MRG_ID" INT(11) [default: NULL]
  "MRG_USERNAME" VARCHAR(100) [default: NULL]
  "MRG_EMAIL" VARCHAR(50) [default: NULL]
  "LAST_TRADES" DATETIME [default: NULL]
  "LAST_ACTIVITY" DATETIME [default: NULL]
  "EXPIRED" DATETIME [default: NULL]
  "MODIFY_TIMESTAMP" INT(11) [not null, default: "0"]

Indexes {
  TIMESTAMP [name: "INDEX_STAMP"]
  LAST_TRADES [name: "INDEX_LAST_TRADES"]
  GROUP [name: "INDEX_GROUP"]
  REGDATE [name: "INDEX_REGDATE"]
  EMAIL [name: "INDEX_EMAIL"]
  MRG_ID [name: "MRG_ID"]
  MRG_USERNAME [name: "MRG_USERNAME"]
  MRG_EMAIL [name: "MRG_EMAIL"]
  LAST_ACTIVITY [name: "LAST_ACTIVITY"]
  EXPIRED [name: "EXPIRED"]
  MODIFY_TIMESTAMP [name: "MODIFY_TIMESTAMP"]
}
}
