Table "open_account" {
  "id" BIGINT(20) [pk, not null, increment]
  "metaserver_id" INT(11) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "platform_id" VARCHAR(20) [not null, default: ""]
  "tipe" INT(1) [not null, default: "0", note: '0=MT4\r\n1=cTrader\r\n2=Gwazy']
  "current_group" VARCHAR(64) [default: NULL]
  "req_time" INT(10) [not null, default: "0"]
  "create_time" INT(10) [not null, default: "0"]
  "contest" INT(1) [not null, default: "0", note: '0=Contest\r\n1=Not Contest']
  "acc_type" INT(1) [not null, default: "0", note: '0=Premium\r\n1=Syariah\r\n2=Basic\r\n3=Forexadana\r\n4=ProTrader\r\n5=Infinite\r\n']
  "origin" TINYINT(1) [not null, default: "0", note: '0=IMS MRG Indo\r\n1=IMS MRG Inter']
  "ct" VARCHAR(20) [default: NULL]
  "lastActivity" DATETIME [default: NULL]
  "lastTrade" DATETIME [default: NULL]
  "expired" DATETIME [default: NULL]
  "cashback" TINYINT(4) [not null, default: "0"]
  "last_balance" DOUBLE [not null, default: "0"]
  "last_equity" DOUBLE [not null, default: "0"]
  "last_margin_level" DOUBLE [not null, default: "0"]
  "last_margin_update" DATETIME [default: NULL]
  "first_depo" DOUBLE [not null, default: "0"]
  "first_depo_idr" DOUBLE [not null, default: "0"]
  "first_depo_tm" DATETIME [default: NULL]
  "first_depo_verifier" INT(11) [default: NULL]
  "first_depo_verify_tm" DATETIME [default: NULL]
  "total_lot" DOUBLE [not null, default: "0"]
  "total_lot_last_count" DATETIME [default: NULL]
  "total_lot_cur_month" DOUBLE [not null, default: "0"]
  "total_profit_cur_month" DOUBLE [not null, default: "0"]
  "total_lot_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_cur_month" DOUBLE [not null, default: "0"]
  "total_mi_cur_month" DOUBLE [not null, default: "0"]
  "total_mo_cur_month" DOUBLE [not null, default: "0"]
  "total_nmi_cur_month_last_count" DATETIME [default: NULL]
  "total_nmi_last_month" DOUBLE [not null, default: "0"]
  "total_mi_last_month" DOUBLE [not null, default: "0"]
  "total_mo_last_month" DOUBLE [not null, default: "0"]
  "total_nmi_last_3months" DOUBLE [not null, default: "0"]
  "total_mi_last_3months" DOUBLE [not null, default: "0"]
  "total_mo_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_last_month" DOUBLE [not null, default: "0"]
  "total_profit_last_month" DOUBLE [not null, default: "0"]
  "total_lot_last_3months" DOUBLE [not null, default: "0"]
  "total_profit_last_3months" DOUBLE [not null, default: "0"]
  "total_lot_monthly_last_count" DATETIME [default: NULL]
  "total_nmi_monthly_last_count" DATETIME [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]

Indexes {
  user_id [name: "user_id"]
  platform_id [name: "platform_id"]
  lastActivity [name: "lastActivity"]
  expired [name: "expired"]
  lastTrade [name: "lastTrade"]
  first_depo_tm [name: "first_depo_tm"]
  first_depo [name: "first_depo"]
  total_lot [name: "total_lot"]
  total_lot_last_count [name: "total_lot_last_count"]
  cashback [name: "cashback"]
  total_lot_last_month [name: "total_lot_last_month"]
  total_nmi_last_month [name: "total_nmi_last_month"]
  total_lot_last_3months [name: "total_lot_last_3months"]
  total_nmi_last_3months [name: "total_nmi_last_3months"]
  total_lot_cur_month [name: "total_lot_cur_month"]
  total_nmi_cur_month [name: "total_nmi_cur_month"]
  total_lot_cur_month_last_count [name: "total_lot_cur_month_last_count"]
  total_nmi_cur_month_last_count [name: "total_nmi_cur_month_last_count"]
  total_profit_cur_month [name: "total_profit_cur_month"]
  total_mi_cur_month [name: "total_mi_cur_month"]
  total_mo_cur_month [name: "total_mo_cur_month"]
  total_mi_last_month [name: "total_mi_last_month"]
  total_mo_last_month [name: "total_mo_last_month"]
  total_mi_last_3months [name: "total_mi_last_3months"]
  total_mo_last_3months [name: "total_mo_last_3months"]
  total_profit_last_month [name: "total_profit_last_month"]
  total_profit_last_3months [name: "total_profit_last_3months"]
  total_lot_monthly_last_count [name: "total_lot_monthly_last_count"]
  total_nmi_monthly_last_count [name: "total_nmi_monthly_last_count"]
  last_balance [name: "last_balance"]
  last_equity [name: "last_equity"]
  last_margin_level [name: "last_margin_level"]
  first_depo_verifier [name: "first_depo_verifier"]
  first_depo_idr [name: "first_depo_idr"]
  first_depo_verify_tm [name: "first_depo_verify_tm"]
  current_group [name: "current_group"]
  last_margin_update [name: "last_margin_update"]
  metaserver_id [name: "metaserver_id"]
}
}
