Table "withdrawal" {
  "id" INT(5) [pk, not null, increment]
  "metaserver_id" INT(10) [not null, default: "1"]
  "user_id" INT(5) [not null]
  "mt4id" VARCHAR(20) [not null]
  "user_bankname" VARCHAR(20) [not null]
  "user_bankaccno" VARCHAR(20) [not null]
  "user_bankreg" VARCHAR(100) [not null]
  "ref_number" VARCHAR(50) [default: ""]
  "nominal" DECIMAL(15,2) [not null]
  "rate" INT(1) [not null, default: "1", note: '1=fixed;2=float']
  "rateval" INT(11) [not null, default: "10000"]
  "time" INT(10) [not null]
  "tipe" INT(11) [not null, default: "2"]
  "status" INT(1) [not null, default: "0", note: '0=pending,1=verified,2=declined']
  "platform" INT(1) [not null, default: "0"]
  "paypal" VARCHAR(50) [default: ""]
  "fee" FLOAT [default: NULL]
  "origin" TINYINT(1) [not null, default: "0"]
  "fxdana" TINYINT(1) [default: NULL, note: '0=pending,1=verified,2=declined']
  "cashier" INT(11) [default: NULL]
  "cashier_complete_tm" DATETIME [default: NULL]
  "cashier_note" TEXT [default: NULL]
  "amount" DOUBLE [default: NULL]
  "settler" INT(11) [default: NULL]
  "settle_order_num" INT(11) [default: NULL]
  "settle_order_tm" DATETIME [default: NULL]
  "settle_note" TEXT [default: NULL]
  "MODIFY_TIME" BIGINT(20) [not null, default: "0"]
  "campaignid" VARCHAR(128) [default: NULL]
  "adid" VARCHAR(128) [default: NULL]

Indexes {
  mt4id [name: "mt4id"]
  user_id [name: "user_id"]
  metaserver_id [name: "metaserver_id"]
  campaignid [name: "campaignid"]
  adid [name: "adid"]
}
}
